// 10 Hoja de ruta e informe: fases por dependencias (supuestos baratos antes de las decisiones de una
// vía), alistamiento con origen, informe de 14 secciones (§ 12) en pantalla y en vista de impresión,
// alerta «sin fuente primaria oficial», relato de fracaso y ficha de reproducibilidad.
import { esc } from "../nucleo/comun.mjs";
import { ES, OK, barra, encabezado, head, mqBar, pestanas, pie } from "./comun3.mjs";
import { ALERTA, PEND, SHA, X, marca, num, revTxt, sec, IMPL_D } from "./m4-comun.mjs";
import { AP_TXT, CATEG, DEC, FASES, ITEMS, RIESGOS_ORD, SUP, SUP_EST, decDe } from "./datos4.mjs";
import { O } from "./m4-decisiones.mjs";

const CORTO = { "dec-identidad": ["directorio", "directory"], "dec-formato": ["formato", "format"], "dec-catalogo": ["catálogo", "catalog"], "dec-ingesta": ["ingesta", "ingestion"], "dec-computo": ["cómputo", "compute"], "dec-proteccion": ["protección", "protection"], "dec-consumo": ["consumo", "consumption"] };
const SUPC = { "sup-federacion": ["federación", "federation"], "sup-equipo": ["equipo", "team"], "sup-registro": ["registro de transacciones", "transaction log"], "sup-tableros": ["tableros", "dashboards"] };
const origen = (o) => {
  if (o.startsWith("dec-")) { const d = decDe(o); return `<span class="origen origen-dec">${ES("decisión", "decision")} <b>${ES(CORTO[o][0], CORTO[o][1])}</b>${d.rev === "una_via" ? ` <span class="mono">· ${ES("una vía", "one-way")}</span>` : ""}</span>`; }
  if (o.startsWith("R-")) return `<span class="origen origen-r">${ES("mitigación de", "mitigation of")} <b>${o}</b></span>`;
  return `<span class="origen origen-sup">${ES("supuesto", "assumption")} <b>${ES(SUPC[o][0], SUPC[o][1])}</b></span>`;
};
const TIPO_I = { tarea: ["tarea", "task", "M-5,-5.5 H5 V5.5 H-5 Z M-2.5,0 L-0.5,2 L3,-2"], verificacion: ["verificación", "check", "M0,-6 L5,-4 V0.5 C5,3.5 2.5,5.5 0,6.5 C-2.5,5.5 -5,3.5 -5,0.5 V-4 Z M-2.3,0 L-0.5,1.8 L2.6,-1.6"] };
const ESTADO_I = { pendiente: ["pendiente", "pending", PEND(12)], hecho: ["hecho", "done", OK], bloqueado: ["bloqueado", "blocked", X(12)] };
const item = (it) => `<li class="item item-${it.estado}"><span class="item-cab"><span class="cod mono">${it.id}</span><span class="item-tipo">${marca(TIPO_I[it.tipo][2], 14, 1.5)}${ES(TIPO_I[it.tipo][0], TIPO_I[it.tipo][1])}</span><span class="item-estado">${ESTADO_I[it.estado][2]}${ES(ESTADO_I[it.estado][0], ESTADO_I[it.estado][1])}</span></span><b>${ES(esc(it.es), esc(it.en))}</b><span class="item-origen">${ES("viene de", "comes from")} ${it.origen.map(origen).join(" ")}</span><small>${ES("cumplido cuando: ", "done when: ")}${ES(esc(it.cumplido[0]), esc(it.cumplido[1]))}</small>${it.estado === "bloqueado" ? `<small class="campo-aviso">${X(12)}${ES("R-1 no tiene mitigación declarada: la tarea no puede empezar", "R-1 has no declared mitigation: the task cannot start")}</small>` : ""}</li>`;
const fases = `<ol class="fases">${FASES.map((f) => `<li class="fase"><header><span class="ojo">${ES(`Fase ${f.n}`, `Phase ${f.n}`)} · ${ES(f.sem[0], f.sem[1])}</span><h3>${ES(f.es, f.en)}</h3></header><ul class="items">${ITEMS.filter((i) => i.fase === f.n).map(item).join("")}</ul></li>`).join("")}</ol><p class="kit-nota">${ES("Las fases salen de las dependencias. Regla del caso: las pruebas baratas de los supuestos van antes de las decisiones de una vía que sostienen. Ningún ítem existe sin origen.", "Phases come from the dependencies. Case rule: the cheap tests of the assumptions go before the one-way decisions they support. No item exists without an origin.")}</p>`;

const traza = `<div class="traza tarjeta"><p class="ojo">${ES("Trazabilidad de un ítem", "Traceability of one item")}</p><ol class="traza-cadena"><li><span class="cod mono">V-02</span><b>${ES("Grupos de acceso creados en el directorio", "Access groups created in the directory")}</b><small>${ES("verificación · identidad y acceso · fase 2", "check · identity and access · phase 2")}</small></li><li><span class="cod mono">←</span><b>${ES("Decisión «Relación con el directorio del grupo»", "Decision “Relationship with the group directory”")}</b><small>${revTxt("una_via")} · ${ES("espera una prueba · fase 1", "awaiting a test · phase 1")}</small></li><li><span class="cod mono">←</span><b>${ES("Supuesto «el directorio admite federación»", "Assumption “the directory supports federation”")}</b><small>${ES("sin probar · criticidad alta", "untested · high criticality")}</small></li><li><span class="cod mono">←</span><b>${ES("T-01 Consulta escrita al equipo de identidad", "T-01 Written query to the identity team")}</b><small>${ES("prueba barata · fase 0 · vence 2026-10-09", "cheap test · phase 0 · due 2026-10-09")}</small></li></ol></div>`;
const alistamiento = `${traza}<div class="kit-grid alist">${Object.entries(CATEG).map(([k, [es, en]]) => { const its = ITEMS.filter((i) => i.cat === k && i.tipo === "verificacion"); return `<section class="tarjeta"><h3>${ES(es, en)} <span class="mono">${its.filter((i) => i.estado === "hecho").length}/${its.length}</span></h3><ul class="items">${its.map(item).join("")}</ul></section>`; }).join("")}</div>`;

// ---------------------------------------------------------------- informe (§ 12, 14 secciones)
const palabras = (s) => s.trim().split(/\s+/).length;
const LIDER = { es: "Norte y Ejemplo quedan en empate técnico: 3 puntos de diferencia, menos que el margen de 5. La recomendación es moderada. Antes de elegir, prueben dos supuestos baratos y decidan primero el directorio, el formato y el catálogo, que no tienen vuelta atrás.", en: "North and Example are in a technical tie: 3 points apart, less than the 5-point margin. The recommendation is moderate. Before choosing, run two cheap assumption tests and decide the directory, the format and the catalog first: they have no way back." };
for (const l of ["es", "en"]) if (palabras(LIDER[l]) > 50) throw new Error(`resumen de líder ${l}: ${palabras(LIDER[l])} palabras`);
const RELATO = { es: "Es marzo de 2027 y el proyecto se detuvo. Elegimos la plataforma por el puntaje y nadie probó si el directorio del grupo aceptaba la federación: no la aceptaba sin una licencia nueva. Rehicimos los permisos dos veces, el catálogo quedó por ambiente y la auditoría clínica no pudo reconstruir quién vio qué.", en: "It is March 2027 and the project has stopped. We chose the platform by its score and nobody checked whether the group directory accepted federation: it did not, not without a new licence. We rebuilt the permissions twice, the catalog ended up split by environment and the clinical audit could not reconstruct who saw what." };
const S = (n, es, en, cuerpo, salto = false) => `${salto ? `<hr class="salto" data-es="salto de página" aria-hidden="true">` : ""}<section class="inf-sec" id="s${n}"><h2><span class="mono">${String(n).padStart(2, "0")}</span>${ES(es, en)}</h2>${cuerpo}</section>`;
const unaVia = DEC.filter((d) => d.rev === "una_via");
const top3 = RIESGOS_ORD.slice(0, 3);
const secciones = [
  S(1, "Resumen para quien decide", "Summary for the decision-maker", `<p class="inf-lider">${ES(LIDER.es, LIDER.en)}</p><p class="inf-presupuesto mono">${ES(`${palabras(LIDER.es)} palabras · 1 término explicado («empate técnico») · lectura en voz alta < 20 s`, `${palabras(LIDER.en)} words · 1 explained term (“technical tie”) · read aloud < 20 s`)}</p><div class="dos"><div><h3>${ES("Recomendación", "Recommendation")}</h3><p>${ALERTA()} ${ES("Empate técnico entre Norte (78,8) y Ejemplo (75,8). Robustez moderada (frontera): Ejemplo gana en el 69,4 % de las combinaciones de pesos.", "Technical tie between North (78.8) and Example (75.8). Moderate robustness (borderline): Example wins in 69.4 % of weight combinations.")}</p><h3>${ES("Tres decisiones de una vía", "Three one-way decisions")}</h3><ol class="inf-lista">${unaVia.map((d) => `<li>${ES(esc(d.es), esc(d.en))}</li>`).join("")}</ol></div><div><h3>${ES("Tres riesgos principales", "Three main risks")}</h3><ol class="inf-lista">${top3.map((r) => `<li>${r.id} · ${ES(esc(r.modo[0]), esc(r.modo[1]))} <span class="mono">${ES(AP_TXT[r.ap][0], AP_TXT[r.ap][1])}${r.mit ? "" : ES(" · sin mitigación", " · no mitigation")}</span></li>`).join("")}</ol></div></div>`),
  S(2, "El caso", "The case", `<p>${ES("Hospital Ficticio de la Sabana: 400 camas, un sistema de admisiones propio y un grupo hospitalario con directorio de identidad común. Quiere indicadores de ocupación del día y un agente que responda preguntas sobre admisiones.", "Fictional Hospital of La Sabana: 400 beds, its own admissions system and a hospital group with a shared identity directory. It wants same-day occupancy indicators and an agent that answers questions about admissions.")}</p><p class="mono">${ES("Restricciones: datos clínicos en el país (elimina a Este) · servicio gestionado · decisión «una plataforma» (respondida).", "Constraints: clinical data in the country (eliminates East) · managed service · “one platform” decision (answered).")}</p><p>${ES("Pesos con su origen: gobierno 25 (comité clínico) · transformación 12 y costo 12 · almacenamiento, consumo 10 · ingesta, cumplimiento 8 · IA, equipo 5 · apertura 3 · operación 2.", "Weights with their origin: governance 25 (clinical committee) · transformation 12 and cost 12 · storage, consumption 10 · ingestion, compliance 8 · AI, team 5 · openness 3 · operations 2.")}</p>`),
  S(3, "Matriz comparativa", "Comparison matrix", `<p>${ES("Once criterios por tres plataformas, cada puntaje con su evidencia, madurez y vigencia (la matriz completa está en la pantalla 08).", "Eleven criteria by three platforms, each score with its evidence, maturity and freshness (the full matrix is on screen 08).")}</p><div class="tabla-marco"><table class="tabla"><thead><tr><th>${ES("Plataforma", "Platform")}</th><th>Total</th><th>${ES("Mínimo de esenciales", "Minimum of essentials")}</th><th>${ES("Evidencia limitante", "Limiting evidence")}</th></tr></thead><tbody><tr><td>Norte</td><td class="mono">${num(78.75)}</td><td class="mono">3/4</td><td>${ES("IA 0/4", "AI 0/4")}</td></tr><tr><td>Ejemplo</td><td class="mono">${num(75.75)}</td><td class="mono">3/4</td><td>${ES("IA 2/4 (tope por madurez)", "AI 2/4 (maturity cap)")}</td></tr><tr><td>Sur</td><td class="mono">${num(63.75)}</td><td class="mono">2/4</td><td>${ES("Gobierno 2/4", "Governance 2/4")}</td></tr></tbody></table></div>`, true),
  S(4, "Pros y contras", "Pros and cons", `<ul class="pros"><li>${OK}<span>${ES("Ejemplo: apertura 4/4 y almacenamiento 4/4.", "Example: openness 4/4 and storage 4/4.")}</span></li><li>${OK}<span>${ES("Norte: gobierno 4/4, la mejor en un criterio esencial.", "North: governance 4/4, best on an essential criterion.")}</span></li><li>${X()}<span>${ES("Norte: IA 0/4; Sur: gobierno 2/4 en un criterio esencial.", "North: AI 0/4; South: governance 2/4 on an essential criterion.")}</span></li></ul>`),
  S(5, "Robustez", "Robustness", `<p>${ES("Punto de inversión de gobierno: 14,8 (Ejemplo pasa a primera por debajo); empate técnico hasta 31,9. Simulación: 10 000 combinaciones con semilla; Ejemplo 69,4 % ± 0,9 → moderada (frontera). Umbrales 70 / 50 / 5 declarados como convención.", "Governance reversal point: 14.8 (Example becomes first below it); technical tie up to 31.9. Simulation: 10,000 seeded combinations; Example 69.4 % ± 0.9 → moderate (borderline). Thresholds 70 / 50 / 5 declared as a convention.")}</p>`),
  S(6, "Estructura de decisiones", "Decision structure", `<div class="tabla-marco"><table class="tabla"><thead><tr><th>${ES("Onda", "Wave")}</th><th>${ES("Decisión", "Decision")}</th><th>${ES("Reversibilidad", "Reversibility")}</th><th>${ES("Opción recomendada", "Recommended option")}</th></tr></thead><tbody>${O.ondas.flatMap((ids, i) => ids.map((id) => { const d = decDe(id); return `<tr><td class="mono">${i + 1}</td><td>${ES(esc(d.es), esc(d.en))}</td><td>${revTxt(d.rev)}</td><td>${ES(esc(d.reco[0]), esc(d.reco[1]))}</td></tr>`; })).join("")}</tbody></table></div>`, true),
  S(7, "Decisiones implícitas detectadas", "Implicit decisions detected", `<ul class="pros">${DEC.filter((d) => d.impl).map((d) => `<li>${marca(IMPL_D, 14, 2)}<span>${ES(esc(d.es), esc(d.en))}</span></li>`).join("")}<li>${OK}<span>${ES("¿Una plataforma o combinación? Respondida en el perfil: una.", "One platform or a combination? Answered in the profile: one.")}</span></li></ul>`),
  S(8, "Riesgos", "Risks", `<div class="tabla-marco"><table class="tabla"><thead><tr><th>${ES("Riesgo", "Risk")}</th><th>S·O·D</th><th>${ES("Prioridad", "Priority")}</th><th>${ES("Residual", "Residual")}</th></tr></thead><tbody>${RIESGOS_ORD.map((r) => `<tr><td>${r.id} · ${ES(esc(r.modo[0]), esc(r.modo[1]))}</td><td class="mono">${r.s}·${r.o}·${r.d}</td><td class="mono">${ES(AP_TXT[r.ap][0], AP_TXT[r.ap][1])}</td><td class="mono">${r.apRes ? ES(AP_TXT[r.apRes][0], AP_TXT[r.apRes][1]) : `<span class="campo-aviso">${X(12)}${ES("sin mitigación", "no mitigation")}</span>`}</td></tr>`).join("")}</tbody></table></div>`),
  S(9, "Supuestos críticos y pruebas baratas", "Critical assumptions and cheap tests", `<ul class="pros">${SUP.map((q) => `<li>${q.estado === "sin_probar" ? ALERTA() : q.estado === "confirmado" ? OK : X()}<span>${ES(esc(q.es), esc(q.en))}<small>${ES(SUP_EST[q.estado][0], SUP_EST[q.estado][1])} · ${ES(esc(q.prueba[0]), esc(q.prueba[1]))}</small></span></li>`).join("")}</ul>`, true),
  S(10, "Relato de fracaso", "Failure story", `<blockquote class="relato">«${ES(RELATO.es, RELATO.en)}»</blockquote><p class="mono">${ES("Escrito por el comité del caso el 2026-09-24, antes del análisis (pre-mortem). La herramienta no lo redacta: lo guarda y enlaza lo que generó: R-1 y el supuesto de federación.", "Written by the case committee on 2026-09-24, before the analysis (pre-mortem). The tool does not write it: it stores it and links what it produced: R-1 and the federation assumption.")}</p>`),
  S(11, "Hoja de ruta por fases", "Phased roadmap", `<ol class="inf-lista">${FASES.map((f) => `<li><b>${ES(`Fase ${f.n}`, `Phase ${f.n}`)} · ${ES(f.es, f.en)}</b> <span class="mono">${ES(f.sem[0], f.sem[1])} · ${ITEMS.filter((i) => i.fase === f.n).length} ${ES("ítems", "items")}</span></li>`).join("")}</ol>`),
  S(12, "Lista de verificación de alistamiento", "Readiness checklist", `<ul class="inf-lista">${Object.entries(CATEG).map(([k, [es, en]]) => { const its = ITEMS.filter((i) => i.cat === k && i.tipo === "verificacion"); return `<li>${ES(es, en)} <span class="mono">${its.filter((i) => i.estado === "hecho").length}/${its.length}</span></li>`; }).join("")}</ul>`, true),
  S(13, "Alertas", "Alerts", `<ul class="alertas"><li class="alerta-fuerte">${X()}<span><b>${ES("Sin fuente primaria oficial", "No official primary source")}</b> · ${ES("evi-sur-0018 (asistente de la Plataforma Sur) se apoya solo en el blog de un integrador certificado por el fabricante.", "evi-sur-0018 (South Platform assistant) rests only on the blog of an integrator certified by the vendor.")}</span></li><li>${ALERTA()}<span><b>${ES("Por revisar", "To review")}</b> · ${ES("Inteligencia artificial de la Plataforma Ejemplo, verificada hace 41 días.", "Example Platform artificial intelligence, verified 41 days ago.")}</span></li><li>${ALERTA()}<span><b>${ES("En vista previa", "In preview")}</b> · ${ES("agente de datos (Ejemplo), catálogo (Norte), asistente (Sur).", "data agent (Example), catalog (North), assistant (South).")}</span></li><li>${ALERTA()}<span><b>${ES("Supuestos críticos sin probar", "Critical untested assumptions")}</b> · ${ES("federación del directorio; el equipo opera el motor.", "directory federation; the team operates the engine.")}</span></li><li>${X()}<span><b>${ES("Riesgo de acción alta sin mitigación", "High-action risk without mitigation")}</b> · ${ES("R-1: el informe queda en borrador hasta resolverlo.", "R-1: the report stays in draft until it is resolved.")}</span></li></ul>`),
  S(14, "Ficha de reproducibilidad", "Reproducibility sheet", `<dl class="evidencia-meta repro"><div><dt>${ES("Instantánea de la base", "Base snapshot")}</dt><dd>2026-09-26 · ${SHA("8d2c4e", "f31a")}</dd></div><div><dt>${ES("Perfil del caso", "Case profile")}</dt><dd>v3 · ${SHA("5a71b3", "e9c2")}</dd></div><div><dt>${ES("Fecha de evaluación", "Evaluation date")}</dt><dd class="mono">2026-09-26</dd></div><div><dt>${ES("Semilla e iteraciones", "Seed and iterations")}</dt><dd class="mono">20260926 · 10 000 · sfc32</dd></div><div><dt>${ES("Umbrales (convención)", "Thresholds (convention)")}</dt><dd class="mono">70 % · 50 % · ${ES("empate", "tie")} 5</dd></div><div><dt>${ES("Tabla de prioridad de acción", "Action priority table")}</dt><dd class="mono">v0 · ${ES("severidad primero", "severity first")}</dd></div><div><dt>${ES("Versión de la herramienta", "Tool version")}</dt><dd class="mono">Big-D 0.1.0</dd></div><div><dt>${ES("Huella de este informe", "This report's fingerprint")}</dt><dd>${SHA("e41f07", "8b2d")} <span class="mono">${ES("igual en Node, Chromium, Firefox y WebKit", "equal in Node, Chromium, Firefox and WebKit")}</span></dd></div></dl><p class="kit-nota">${ES("Declaración del autor: conoce Microsoft Fabric más a fondo que las demás plataformas. Todo en este informe es ficticio.", "Author's statement: the author knows Microsoft Fabric more deeply than the other platforms. Everything in this report is fictional.")}</p>`),
];
const indice = `<nav class="inf-indice" aria-label="${"Secciones del informe"}"><p class="ojo">${ES("14 secciones", "14 sections")}</p><ol>${[["Resumen para quien decide", "Summary for the decision-maker"], ["El caso", "The case"], ["Matriz comparativa", "Comparison matrix"], ["Pros y contras", "Pros and cons"], ["Robustez", "Robustness"], ["Estructura de decisiones", "Decision structure"], ["Decisiones implícitas", "Implicit decisions"], ["Riesgos", "Risks"], ["Supuestos y pruebas baratas", "Assumptions and cheap tests"], ["Relato de fracaso", "Failure story"], ["Hoja de ruta", "Roadmap"], ["Alistamiento", "Readiness"], ["Alertas", "Alerts"], ["Reproducibilidad", "Reproducibility"]].map(([es, en], i) => `<li><a href="#s${i + 1}"><span class="mono">${String(i + 1).padStart(2, "0")}</span>${ES(es, en)}</a>${i === 12 ? ` <span class="mono">5</span>` : ""}</li>`).join("")}</ol></nav>`;
const informeHTML = `<div class="informe-marco">${indice}<article class="informe"><header class="inf-cabeza"><p class="ojo">${ES("Informe · borrador", "Report · draft")} · 2026-09-26</p><h2 class="inf-titulo">${ES("Hospital Ficticio de la Sabana: elección de plataforma de datos", "Fictional Hospital of La Sabana: data platform choice")}</h2><p class="meta"><span>${ES("perfil v3", "profile v3")}</span><span class="punto">·</span><span>${ES("instantánea 2026-09-26", "snapshot 2026-09-26")}</span><span class="punto">·</span>${SHA("e41f07", "8b2d")}</p><p class="inf-cabeza-pag mono">${ES("Big-D · informe · página 1 de 5", "Big-D · report · page 1 of 5")}</p></header>${secciones.join("")}</article></div>`;

export const informe = `${head({ es: "Hoja de ruta e informe", en: "Roadmap and report" })}
<body>
${mqBar("10 Hoja de ruta e informe", "Estado de la maqueta", [["fases", "vista:fases", "fases"], ["alistamiento", "vista:alistamiento", "ítem con origen"], ["informe", "vista:informe", "informe en pantalla"], ["impresion", "vista:impresion", "vista de impresión"]], [["fases", "<b>Fases.</b> Cuatro fases por dependencias: primero las pruebas baratas de los supuestos, después las decisiones de una vía. Cada ítem dice su tipo (tarea o verificación), de dónde viene (decisión, mitigación o supuesto), cuándo está cumplido y su estado; T-07 está bloqueado porque R-1 no tiene mitigación."], ["alistamiento", "<b>Ítem con origen.</b> La cadena de V-02 hasta la prueba barata que la destraba, y la lista de alistamiento por las siete categorías, cada ítem con su origen."], ["informe", "<b>Informe en pantalla.</b> Las 14 secciones con índice. El resumen para quien decide cumple el presupuesto (≤ 50 palabras, un término explicado) y lo dice; la sección 13 trae la alerta «sin fuente primaria oficial»; el relato de fracaso lo escribe el comité, no la herramienta. Cambia a EN arriba: está redactado, no traducido."], ["impresion", "<b>Vista de impresión.</b> El mismo informe como papel claro (también en tema oscuro), con cabecera de página y saltos marcados. «Imprimir» abre el diálogo del navegador, que usa la misma hoja."]])}
${barra("caso")}
<main class="pagina" id="contenido">
  ${encabezado({ es: "Caso · hoja de ruta e informe", en: "Case · roadmap and report" }, { es: "Hospital Ficticio de la Sabana", en: "Fictional Hospital of La Sabana" }, { es: "Del «cuál» al «cómo»: fases por dependencias, alistamiento con origen y un informe que cualquiera puede reproducir.", en: "From “which” to “how”: phases by dependencies, readiness with an origin and a report anyone can reproduce." }, `<p class="meta"><b>${PEND()}${ES("informe en borrador", "report in draft")}</b><span class="punto">·</span><span>${ES("bloqueado por R-1 (alta sin mitigación)", "blocked by R-1 (high without mitigation)")}</span><span class="punto">·</span><span>${ES(`${ITEMS.length} ítems en 4 fases`, `${ITEMS.length} items in 4 phases`)}</span></p>`, false)}
  ${pestanas("caso", "informe.html")}
  <ul class="niveles kit-niveles" aria-label="Vistas"><li><a href="#fases" data-si="vista:fases" aria-current="page"><span class="n">a</span>${ES("Hoja de ruta", "Roadmap")}</a><a href="#fases" data-si="vista:alistamiento|informe|impresion"><span class="n">a</span>${ES("Hoja de ruta", "Roadmap")}</a></li><li><a href="#alist" data-si="vista:alistamiento" aria-current="page"><span class="n">b</span>${ES("Alistamiento", "Readiness")}</a><a href="#alist" data-si="vista:fases|informe|impresion"><span class="n">b</span>${ES("Alistamiento", "Readiness")}</a></li><li><a href="#informe" data-si="vista:informe|impresion" aria-current="page"><span class="n">c</span>${ES("Informe", "Report")}</a><a href="#informe" data-si="vista:fases|alistamiento"><span class="n">c</span>${ES("Informe", "Report")}</a></li></ul>
  <div data-si="vista:fases">${sec("Hoja de ruta por fases", "Phased roadmap", "", fases, ' id="fases"')}</div>
  <div data-si="vista:alistamiento">${sec("Lista de verificación de alistamiento", "Readiness checklist", ES("Por categoría; cada ítem sabe de qué decisión, mitigación o supuesto viene y cuándo está cumplido.", "By category; each item knows which decision, mitigation or assumption it comes from and when it is done."), alistamiento, ' id="alist"')}</div>
  <div data-si="vista:informe|impresion" id="informe">
    <div class="kit-fila inf-acciones"><span class="alterna" role="group" data-aria-es="Idioma del informe" data-aria-en="Report language"><button type="button" data-lang-set="es" lang="es-ES">ES</button><span class="sep">/</span><button type="button" data-lang-set="en" lang="en-US">EN</button></span><button type="button" class="boton boton-sec" data-imprimir>${ES("Imprimir", "Print")}</button><span class="mono">${ES("el informe se emite en los dos idiomas, redactados por plantilla", "the report is issued in both languages, written from templates")}</span></div>
    ${informeHTML}
  </div>
</main>
<script src="assets/informe.js" defer></script>
${pie}`;
