import { MODO, TIPO, MADUREZ } from "../nucleo/datos.mjs";
import { MODO_MARCA, TIPO_GLIFO, MARCA } from "../nucleo/glifos.mjs";
import { ES, CHEVRON, barra, head, mqBar, pie } from "./comun3.mjs";
import { escribir } from "../pulir.mjs";
const glifo = (tp, s = 18) => { const g = TIPO_GLIFO[tp.g]; return `<svg class="lg-${tp.t}" viewBox="-9 -9 18 18" width="${s}" height="${s}" aria-hidden="true">${g.relleno ? `<path d="${g.d}" fill="currentColor"/>` : `<path d="${g.d}" fill="none" stroke="currentColor" stroke-width="${g.trazo}"/>`}</svg>`; };
const marca = (d, s = 14, w = 1.8) => `<svg viewBox="-8 -8 16 16" width="${s}" height="${s}" aria-hidden="true"><path d="${d}" fill="none" stroke="currentColor" stroke-width="${w}" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const sem = (v, txt) => `<span class="semaforo semaforo-${v}"><svg viewBox="-8 -8 16 16" width="16" height="16" aria-hidden="true">${v === "vencido" ? `<circle r="7" fill="currentColor"/><path d="${MARCA.vencido}" fill="none" stroke="var(--fondo)" stroke-width="1.8" stroke-linecap="round"/>` : `<circle r="7" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="${MARCA[v]}" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>`}</svg>${txt}</span>`;
const sec = (id, es, en, nota, cuerpo) => `<section class="kit-sec" id="${id}"><h2>${ES(es, en)}</h2><p class="kit-nota">${nota}</p>${cuerpo}</section>`;
const html = `${head({ es: "Kit de componentes", en: "Component kit" })}
<body>
${mqBar("Kit de componentes (design system v0.5)", "Estado de la maqueta", [["kit", "vista:kit", "todo"]], [["kit", "<b>Kit.</b> Todos los componentes canon del design system, con sus estados, en el tema y el idioma que elijas arriba. Lo que no es del atlas (evidencia, control de peso, prioridad de acción, estados de carga y error) se ve aquí por primera vez y se usa en las miradas 3 y 4."]])}
${barra("kit")}
<main class="pagina" id="contenido">
  <div class="encabezado"><div><span class="ojo">${ES("Design system · v0.3 · componentes canon", "Design system · v0.3 · canon components")}</span><h1>${ES("Kit de componentes", "Component kit")}</h1><p class="sub">${ES("Instrumental, técnico, legible. Sin píldoras ni rellenos: filetes, texto y aire. El color pertenece a la gramática del diagrama.", "Instrumental, technical, legible. No pills, no fills: rules, text and air. Colour belongs to the diagram's grammar.")}</p></div></div>
  <nav class="kit-indice" aria-label="Secciones del kit"><a href="#tipos">${ES("Gramática", "Grammar")}</a><a href="#semaforo">${ES("Vigencia", "Freshness")}</a><a href="#controles">${ES("Controles", "Controls")}</a><a href="#evidencia">${ES("Evidencia", "Evidence")}</a><a href="#peso">${ES("Peso", "Weight")}</a><a href="#prioridad">${ES("Prioridad", "Priority")}</a><a href="#estados">${ES("Estados", "States")}</a><a href="#texto">${ES("Texto", "Text")}</a></nav>

${sec("tipos", "Gramática del diagrama: tipos, modos, madurez", "Diagram grammar: types, modes, maturity", ES("Cada tipo = color + glifo + código. Cada modo = trazo + marcador. La madurez es un medidor de llenado; solo se muestra cuando no es «disponible».", "Each type = colour + glyph + code. Each mode = stroke + marker. Maturity is a fill gauge; shown only when not “available”."), `
  <ul class="lg-lista dos">${Object.values(TIPO).map((tp) => `<li>${glifo(tp)}<span class="cod">${ES(tp.es[0], tp.en[0])}</span><span>${ES(tp.es[1], tp.en[1])}</span></li>`).join("")}</ul>
  <ul class="lg-lista lg-modos kit-modos">${Object.keys(MODO).map((m) => { const mk = MODO_MARCA[m]; const dash = { "por-lotes": 'stroke-dasharray="8 5"', continuo: "", "a-demanda": 'stroke-dasharray="0.1 5.5" stroke-linecap="round" stroke-width="2.8"', "sin-copia": "" }[m]; const linea = m === "sin-copia" ? `<path d="M2,7 H38" stroke="currentColor" stroke-width="6.5"/><path d="M2,7 H38" stroke="var(--fondo)" stroke-width="2.5"/>` : `<path d="M2,7 H38" stroke="currentColor"${dash.includes("stroke-width") ? "" : ' stroke-width="2"'} ${dash}/>`; const mm = mk.relleno === "mixto" ? `<path d="${mk.d}" fill="currentColor" stroke="currentColor" stroke-width="1.2" transform="translate(52,7)"/>` : `<path d="${mk.d}" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" transform="translate(52,7)"/>`; return `<li><svg viewBox="0 0 62 14" width="62" height="14" aria-hidden="true" fill="none">${linea}${mm}</svg><span>${ES(MODO[m].es[0], MODO[m].en[0])} — ${ES(MODO[m].es[1], MODO[m].en[1])}</span></li>`; }).join("")}</ul>
  <ul class="lg-lista kit-madurez">${Object.values(MADUREZ).map((m) => { const lleno = m.nivel >= 0 ? Math.round((11 * m.nivel) / 4) : 0; return `<li><svg viewBox="-6 -8 12 16" width="12" height="16" aria-hidden="true"><rect x="-3.5" y="-5.5" width="7" height="11" rx="1.5" fill="none" stroke="currentColor" stroke-width="1.2"${m.nivel === 0 ? ' stroke-dasharray="2 1.5"' : ""}/>${lleno ? `<rect x="-3.5" y="${(5.5 - lleno).toFixed(1)}" width="7" height="${lleno}" rx="1" fill="currentColor"/>` : ""}${m.nivel < 0 ? '<path d="M-3.5,5.5 L3.5,-5.5" stroke="currentColor" stroke-width="1.4"/>' : ""}</svg><span class="cod">${m.nivel < 0 ? "−" : m.nivel}/4</span><span>${ES(m.largo.es, m.largo.en)}</span></li>`; }).join("")}</ul>`)}

${sec("semaforo", "Semáforo de vigencia", "Freshness traffic light", ES("Símbolo + texto + días, en tinta: jamás un matiz de capacidad. Dentro del mapa solo se marca la excepción.", "Symbol + text + days, in ink: never a capability hue. Inside the map only the exception is marked."), `
  <div class="kit-fila">${sem("vigente", ES("vigente · hace 6 días", "current · 6 days ago"))}${sem("revisar", ES("por revisar · 34 días", "to review · 34 days"))}${sem("vencido", ES("vencido · 63 días", "expired · 63 days"))}</div>
  <p class="kit-nota">${ES("Umbrales declarados: 30 y 60 días desde la verificación, contados con la fecha de consulta como entrada.", "Declared thresholds: 30 and 60 days since verification, counted with the query date as input.")}</p>`)}

${sec("controles", "Controles", "Controls", ES("Botón principal lleno de tinta; secundario en contorno; enlace-botón con línea inferior; alternador en mono; pestañas con subrayado; índice de capas. Todo con foco visible de 2 px.", "Primary button filled with ink; secondary outlined; link-button with bottom rule; toggle in mono; underlined tabs; layer index. All with a 2 px visible focus."), `
  <div class="kit-fila"><button type="button" class="boton">${ES("Aprobar propuesta", "Approve proposal")}</button><button type="button" class="boton boton-sec">${ES("Anterior", "Previous")}</button><button type="button" class="boton" disabled>${ES("Sin cambios", "No changes")}</button><button type="button" class="enlace-boton">${ES("Cambiar de plataforma", "Switch platform")}${CHEVRON}</button><span class="alterna"><button type="button" aria-pressed="true">ES</button><span class="sep">/</span><button type="button">EN</button></span></div>
  <ul class="niveles kit-niveles" aria-label="Pestañas"><li><a href="#controles" aria-current="page"><span class="n">01</span>${ES("Actual", "Current")}</a></li><li><a href="#controles"><span class="n">02</span>${ES("Otra", "Another")}</a></li><li><span class="pend"><span class="n">03</span>${ES("Pendiente", "Pending")}</span></li></ul>
  <div class="kit-fila"><label class="campo"><span class="campo-etiqueta">${ES("Fecha de evaluación", "Evaluation date")}</span><input type="text" class="mono" value="2026-09-26"></label><label class="campo campo-error"><span class="campo-etiqueta">${ES("Semilla", "Seed")}</span><input type="text" class="mono" value="abc" aria-invalid="true" aria-describedby="e1"><span class="campo-aviso" id="e1">${marca(MARCA.vencido, 12)}${ES("Debe ser un entero.", "Must be an integer.")}</span></label><label class="campo"><span class="campo-etiqueta">${ES("Plataforma", "Platform")}</span><span class="select"><select lang="es" data-aria-es="Plataforma" data-aria-en="Platform"><option>Plataforma Ejemplo (ficticia)</option><option>Plataforma Norte (ficticia)</option></select><select lang="en" data-aria-es="Plataforma" data-aria-en="Platform"><option>Example Platform (fictional)</option><option>North Platform (fictional)</option></select>${CHEVRON}</span></label></div>`)}

${sec("evidencia", "Tarjeta de evidencia", "Evidence card", ES("Fuente · fecha · madurez · conflicto de interés · vigencia. La cita textual va entre comillas latinas; la verificación por código, en mono.", "Source · date · maturity · conflict of interest · freshness. The verbatim quote in guillemets; code verification in mono."), `
  <div class="kit-grid">
  <article class="evidencia"><header><span class="cod">EV-0142</span>${sem("vigente", ES("vigente · 6 d", "current · 6 d"))}<span class="evidencia-estado">${ES("aprobada", "approved")}</span></header><p class="evidencia-afirma">${ES("Las tablas limpias se leen en su lugar desde el modelo semántico, sin copia.", "Clean tables are read in place from the semantic model, without a copy.")}</p><blockquote class="evidencia-cita">«${ES("El modelo lee las tablas abiertas directamente mediante el catálogo.", "The model reads the open tables directly through the catalog.")}»</blockquote><dl class="evidencia-meta"><div><dt>${ES("Fuente", "Source")}</dt><dd><a href="https://example.org/ficticia/semantica">${ES("Documentación ficticia del modelo semántico", "Fictional semantic model documentation")}</a> <span class="mono">oficial · 2026-08-30</span></dd></div><div><dt>${ES("Madurez", "Maturity")}</dt><dd>${ES("Disponible de forma general", "Generally available")}</dd></div><div><dt>${ES("Conflicto de interés", "Conflict of interest")}</dt><dd>${ES("Ninguno declarado", "None declared")}</dd></div><div><dt>${ES("Verificación", "Verification")}</dt><dd class="mono">curl · 200 · 2026-09-20 · sha256 3f9a…c21e</dd></div></dl></article>
  <article class="evidencia evidencia-propuesta"><header><span class="cod">PR-0007</span>${sem("revisar", ES("por revisar · 34 d", "to review · 34 d"))}<span class="evidencia-estado">${ES("propuesta", "proposal")}</span></header><p class="evidencia-afirma">${ES("El agente de preguntas pasa a disponible de forma general.", "The question agent becomes generally available.")}</p><blockquote class="evidencia-cita evidencia-no-verificada">«${ES("El agente está disponible para todos los clientes.", "The agent is available to all customers.")}» <span class="mono">${marca(MARCA.vencido, 12)} ${ES("cita no verificada", "quote not verified")}</span></blockquote><dl class="evidencia-meta"><div><dt>${ES("Fuente", "Source")}</dt><dd><a href="https://example.org/ficticia/agentes">${ES("Anuncio ficticio del agente", "Fictional agent announcement")}</a> <span class="mono">${ES("anuncio", "announcement")} · 2026-09-10</span></dd></div><div><dt>${ES("Conflicto de interés", "Conflict of interest")}</dt><dd>${ES("Fuente del fabricante", "Vendor source")}</dd></div></dl><footer class="kit-fila"><button type="button" class="boton">${ES("Aprobar", "Approve")}</button><button type="button" class="boton boton-sec">${ES("Rechazar", "Reject")}</button></footer></article>
  </div>`)}

${sec("peso", "Control de peso con rango relativo", "Weight control with relative range", ES("El peso en centésimas; el rango relativo dice entre qué valores el resultado no cambia; el origen, quién lo fijó. El punto de inversión se marca en el control.", "Weight in hundredths; the relative range says between which values the result does not change; the origin, who set it. The reversal point is marked on the control."), `
  <div class="kit-grid">
  <div class="peso"><div class="peso-cabeza"><b>${ES("Gobierno y seguridad", "Governance and security")}</b><span class="mono">25</span></div><div class="peso-barra" role="slider" aria-valuemin="0" aria-valuemax="100" aria-valuenow="25" tabindex="0" data-aria-es="Peso de gobierno y seguridad" data-aria-en="Weight of governance and security"><span class="peso-rango" style="left:18%;width:14%"></span><span class="peso-punto" style="left:25%"></span><span class="peso-inversion" style="left:37%"></span></div><p class="peso-meta"><span class="mono">${ES("rango 18–32", "range 18–32")}</span><span class="punto">·</span><span>${ES("inversión en 37", "reversal at 37")}</span><span class="punto">·</span><span>${ES("origen: comité clínico", "origin: clinical committee")}</span></p></div>
  <div class="peso peso-error"><div class="peso-cabeza"><b>${ES("Suma de pesos", "Sum of weights")}</b><span class="mono">104</span></div><div class="peso-barra" aria-hidden="true"><span class="peso-rango" style="left:0;width:100%"></span><span class="peso-punto" style="left:100%"></span></div><p class="peso-meta campo-aviso">${marca(MARCA.vencido, 12)}${ES("Los pesos deben sumar 100: sobran 4.", "Weights must add up to 100: 4 over.")}</p></div>
  </div>`)}

${sec("prioridad", "Tabla de prioridad de acción", "Action priority table", ES("Severidad primero (AIAG-VDA 2019); el RPN solo ordena dentro de una prioridad. Alta sin mitigación = alerta con símbolo.", "Severity first (AIAG-VDA 2019); RPN only orders within a priority. High without mitigation = alert with symbol."), `
  <div class="tabla-marco"><table class="tabla"><thead><tr><th>${ES("Riesgo", "Risk")}</th><th>S</th><th>O</th><th>D</th><th>${ES("Prioridad", "Priority")}</th><th>${ES("Mitigación", "Mitigation")}</th></tr></thead><tbody>
  <tr class="prioridad-alta-sin"><td>${ES("Datos clínicos visibles sin filtro por fila", "Clinical data visible without row filter")}</td><td class="mono">9</td><td class="mono">4</td><td class="mono">6</td><td><span class="prio prio-alta">${marca("M0,-5 V1.5 M0,4.2 V4.6", 12, 2)}${ES("alta", "high")}</span></td><td><span class="campo-aviso">${marca(MARCA.vencido, 12)}${ES("sin mitigación", "no mitigation")}</span></td></tr>
  <tr><td>${ES("Copia diaria satura el sistema de admisiones", "Daily copy saturates the admissions system")}</td><td class="mono">7</td><td class="mono">5</td><td class="mono">3</td><td><span class="prio prio-alta">${marca("M0,-5 V1.5 M0,4.2 V4.6", 12, 2)}${ES("alta", "high")}</span></td><td>${ES("Captura de cambios desde el mes 2", "Change capture from month 2")}</td></tr>
  <tr><td>${ES("Definiciones distintas del mismo indicador", "Different definitions of the same indicator")}</td><td class="mono">5</td><td class="mono">6</td><td class="mono">4</td><td><span class="prio prio-media">${ES("media", "medium")}</span></td><td>${ES("Modelo semántico único", "Single semantic model")}</td></tr>
  <tr><td>${ES("Factura descubierta a fin de mes", "Bill discovered at month end")}</td><td class="mono">3</td><td class="mono">4</td><td class="mono">2</td><td><span class="prio prio-baja">${ES("baja", "low")}</span></td><td>${ES("Alertas de presupuesto", "Budget alerts")}</td></tr>
  </tbody></table></div>`)}

${sec("estados", "Estados: vacío, carga, error", "States: empty, loading, error", ES("Siempre símbolo + texto. La carga dice qué corre y cuánto lleva; el error de una base que no carga dice campo e id.", "Always symbol + text. Loading says what runs and how far; a base that fails to load says field and id."), `
  <div class="kit-grid tres">
  <div class="estado"><svg viewBox="-12 -12 24 24" width="28" height="28" aria-hidden="true"><rect x="-9" y="-7" width="18" height="14" rx="2" fill="none" stroke="currentColor" stroke-width="1.6" stroke-dasharray="3 2"/></svg><b>${ES("Sin casos todavía", "No cases yet")}</b><p>${ES("Crea el primero desde «Caso».", "Create the first one from “Case”.")}</p></div>
  <div class="estado" role="status"><svg class="carga" viewBox="-12 -12 24 24" width="28" height="28" aria-hidden="true"><circle r="9" fill="none" stroke="currentColor" stroke-width="1.6" stroke-dasharray="40 17"/></svg><b>${ES("Simulación en curso", "Simulation running")}</b><p class="mono">2 400 / 10 000 · sfc32 · ${ES("semilla", "seed")} 20260926</p><div class="progreso" aria-hidden="true"><span style="width:24%"></span></div></div>
  <div class="estado estado-error" role="alert"><svg viewBox="-12 -12 24 24" width="28" height="28" aria-hidden="true"><circle r="9" fill="currentColor"/><path d="M-4,-4 L4,4 M4,-4 L-4,4" stroke="var(--fondo)" stroke-width="2" stroke-linecap="round"/></svg><b>${ES("La base no carga", "The base does not load")}</b><p>${ES("Evidencia sin fecha de verificación.", "Evidence without verification date.")}</p><p class="mono">evidencias/ev-0142.yaml · fecha_verificacion</p></div>
  </div>`)}

${sec("texto", "Texto: registros y jerarquía", "Text: registers and hierarchy", ES("Líder (≤ 50 palabras, sin siglas sin explicar) y experto, sin contradecirse. Ojo en mono, título grande, cuerpo 16, secundario en tinta-2.", "Leader (≤ 50 words, no unexplained acronyms) and expert, never contradicting. Mono eyebrow, big title, 16 body, secondary in ink-2."), `
  <div class="kit-grid"><div><span class="ojo">${ES("Registro de líder", "Leader register")}</span><p class="ficha-lider">${ES("Trae solo lo nuevo o modificado, casi en el momento en que ocurre.", "Brings only what is new or changed, almost as it happens.")}</p><span class="ojo">${ES("Registro de experto", "Expert register")}</span><p>${ES("Lee el registro de transacciones del origen y replica inserciones, actualizaciones y borrados en orden, con reintento y control de duplicados.", "Reads the source's transaction log and replays inserts, updates and deletes in order, with retries and duplicate control.")}</p><p><span class="termino">${ES("registro de transacciones", "transaction log")}</span> ${ES("— término explicado en la ficha.", "— term explained in the card.")}</p></div>
  <div><span class="ojo">${ES("Huellas y códigos", "Fingerprints and codes")}</span><p class="mono">sha256 3f9a1c…c21e</p><p class="mono">/investigar plataforma-ejemplo almacenamiento</p><p class="mono">2026-09-26 · v0.1.0 · ${ES("semilla", "seed")} 20260926</p></div></div>`)}
</main>
${pie}`;
escribir("kit.html", html);
console.log("kit", (html.length / 1024).toFixed(1), "KB");
