// Mirada 3: investigador · base de conocimiento · perfil del caso · comparación. Datos 100 % ficticios
// (Hospital Ficticio de la Sabana; plataformas Ejemplo, Norte, Sur, Este). Los totales, el punto de
// inversión y la banda de empate se CALCULAN aquí con las fórmulas de la investigación científica
// § 1.3 (no se escriben a mano), para que las pantallas no se contradigan.
import fs from "node:fs";
import { BANDA } from "../nucleo/datos.mjs";
import { MARCA } from "../nucleo/glifos.mjs";
import { ES, CHEVRON, OK, barra, encabezado, head, mqBar, pestanas, pie } from "./comun3.mjs";
import { SALIDA } from "../rutas.mjs";
import { CRIT, EMPATE, K, LIMITANTE, MARGEN_EMPATE, PL, RANGO, MISMA_CLASE, ROB, ROB_OTRAS, T, Tk, UMBRAL, W, enteros100, minEs, tEmpateSale, tInv, total } from "./caso.mjs";

const OUT = SALIDA + "/";
const X = (s = 14) => `<svg viewBox="-8 -8 16 16" width="${s}" height="${s}" aria-hidden="true"><circle r="7" fill="currentColor"/><path d="${MARCA.vencido}" fill="none" stroke="var(--fondo)" stroke-width="1.8" stroke-linecap="round"/></svg>`;
const ALERTA = (s = 14) => `<svg viewBox="-8 -8 16 16" width="${s}" height="${s}" aria-hidden="true"><circle r="7" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="${MARCA.revisar}" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>`;
const PEND = (s = 14) => `<svg viewBox="-8 -8 16 16" width="${s}" height="${s}" aria-hidden="true"><circle r="7" fill="none" stroke="currentColor" stroke-width="1.5" stroke-dasharray="2.5 2"/></svg>`;
const EST = (s = 12) => `<svg class="esencial" viewBox="-8 -8 16 16" width="${s}" height="${s}" aria-hidden="true"><path d="M0,-7 L2,-2.2 L7,-1.8 L3.2,1.6 L4.3,6.6 L0,4 L-4.3,6.6 L-3.2,1.6 L-7,-1.8 L-2,-2.2 Z" fill="currentColor"/></svg>`;
const sem = (v, txt) => `<span class="semaforo semaforo-${v}"><svg viewBox="-8 -8 16 16" width="16" height="16" aria-hidden="true">${v === "vencido" ? `<circle r="7" fill="currentColor"/><path d="${MARCA.vencido}" fill="none" stroke="var(--fondo)" stroke-width="1.8" stroke-linecap="round"/>` : `<circle r="7" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="${MARCA[v]}" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>`}</svg>${txt}</span>`;
const sec = (es, en, nota, cuerpo, attrs = "") => `<section class="seccion"${attrs}><h2>${ES(es, en)}</h2>${nota ? `<p class="kit-nota">${nota}</p>` : ""}${cuerpo}</section>`;
const n1 = (x) => x.toFixed(1).replace(".", ",");
const num = (x) => ES(n1(x), x.toFixed(1));
const SHA = (a, b) => `<span class="huella">sha256 <b>${a}</b>…${b}</span>`;

// ---------------------------------------------------------------- datos del caso
const CASO = { es: "Hospital Ficticio de la Sabana", en: "Fictional Hospital of La Sabana" };
const e = PL.find((p) => p.id === "ejemplo"), n = PL.find((p) => p.id === "norte");
const NORTE_CLARA = [...n.s]; NORTE_CLARA[K] = 1;
const T_CLARA = { ejemplo: total(e.s), norte: total(NORTE_CLARA), sur: total(PL[2].s) };
console.log("totales", T, "clara", T_CLARA, "t*", tInv.toFixed(1), "sale del empate en", tEmpateSale, "empate:", EMPATE);
console.log("robustez", ROB.lider, ROB.acept[ROB.lider][0].toFixed(2), "% · empate", ROB.empate.toFixed(2), "% ·", ROB.clase, "· intentos", ROB.intentos, "· otras semillas", ROB_OTRAS.map((r) => `${r.lider} ${r.acept[r.lider][0].toFixed(2)}`).join(" / "));

// ---------------------------------------------------------------- 05 investigador
const BANDAS = ["fuentes", "ingesta", "almacenamiento", "procesamiento", "consumo", "ia", "gobierno", "operacion", "orquestacion"];
const VIG = { fuentes: ["vigente", 6, 1], ingesta: ["vigente", 6, 3], almacenamiento: ["vencido", 63, 2], procesamiento: ["revisar", 34, 2], consumo: ["vigente", 12, 2], ia: ["revisar", 41, 1], gobierno: ["vigente", 6, 3], operacion: ["vigente", 20, 1], orquestacion: ["vigente", 6, 1] };
const VIG_TXT = { vigente: ["vigente", "current"], revisar: ["por revisar", "to review"], vencido: ["vencido", "expired"] };
const dias = (d) => ES(`${d} días`, `${d} days`);
const semLista = (aprobado) => `<ul class="filas sem-lista">${BANDAS.map((b, i) => { let [v, d, f] = VIG[b]; if (aprobado && b === "almacenamiento") { v = "vigente"; d = 0; f = 3; } const venc = v === "vencido"; return `<li${venc ? " data-vencido" : ""}><span class="n">${String(i + 1).padStart(2, "0")}</span><span class="sem-banda">${ES(BANDA[b].es[0], BANDA[b].en[0])}<small>${ES(`${f} ${f === 1 ? "evidencia" : "evidencias"} · verificada hace ${d} días`, `${f} ${f === 1 ? "piece" : "pieces"} of evidence · verified ${d} days ago`)}</small></span>${sem(v, `${ES(VIG_TXT[v][0], VIG_TXT[v][1])} · ${dias(d)}`)}${venc ? `<div class="comando"><code>/investigar plataforma-ejemplo ${b}</code><button type="button" class="boton boton-sec">${ES("Copiar", "Copy")}</button><small>${ES("Se ejecuta en Claude Code, por el curador; la app nunca la lanza. La propuesta llega a «propuestas/» y se revisa abajo.", "Runs in Claude Code, by the curator; the app never launches it. The proposal lands in “propuestas/” and is reviewed below.")}</small></div>` : ""}</li>`; }).join("")}</ul>`;
const AFIRM = [
  { cod: "A-1", es: "El almacén de tablas abiertas conserva versiones de 90 días.", en: "The open-table store keeps 90 days of versions.", cita: ["Time travel: hasta 90 días de historial por tabla.", "Time travel: up to 90 days of history per table."], v: "verificada", fuente: ["Documentación ficticia del almacén", "Fictional store documentation"], url: "https://example.org/ficticia/almacen", sha: "9c41", fecha: "2026-09-26" },
  { cod: "A-2", es: "Nuevo componente: Almacén de objetos frío, en vista previa pública.", en: "New component: Cold object store, in public preview.", cita: ["El almacén frío está disponible en vista previa pública.", "Cold storage is available in public preview."], v: "no_verificable", fuente: ["Anuncio ficticio del almacén frío", "Fictional cold store announcement"], url: "https://example.org/ficticia/frio", sha: null, fecha: "2026-09-26", diff: "nuevo" },
  { cod: "A-3", es: "«Capa cruda» pasa a llamarse «Zona cruda» (mismo componente).", en: "“Raw layer” is renamed “Raw zone” (same component).", cita: ["La Zona cruda (antes Capa cruda) guarda los datos tal como llegan.", "The Raw zone (formerly Raw layer) keeps the data as it arrives."], v: "verificada", fuente: ["Documentación ficticia del almacén", "Fictional store documentation"], url: "https://example.org/ficticia/almacen", sha: "9c41", fecha: "2026-09-26", diff: "renombrado" },
  { cod: "A-4", es: "Cifrado con llaves del cliente disponible de forma general.", en: "Customer-managed encryption keys generally available.", cita: ["Las llaves del cliente están disponibles para todos los planes.", "Customer keys are available on all plans."], v: "no_encontrada", fuente: ["Documentación ficticia de seguridad", "Fictional security documentation"], url: "https://example.org/ficticia/seguridad", sha: "1e07", fecha: "2026-09-26" },
];
const VER = {
  verificada: (a) => `<span class="verif"><b>${OK}${ES("cita verificada", "quote verified")}</b>curl · 200 · ${a.fecha} · sha256 ${a.sha}…</span>`,
  no_verificable: () => `<span class="verif"><b>${ALERTA()}${ES("no verificable por código", "not verifiable by code")}</b>${ES("la página se arma con JavaScript · revisión humana", "page built with JavaScript · human review")}</span>`,
  no_encontrada: (a) => `<span class="verif"><b>${X()}${ES("cita no encontrada", "quote not found")}</b>curl · 200 · ${a.fecha} · sha256 ${a.sha}… · ${ES("rechazada por código", "rejected by code")}</span>`,
};
const afirmacion = (a, aprobado) => { const rech = a.v === "no_encontrada"; const est = rech ? `<span class="insignia insignia-llena">${X(12)}${ES("rechazada", "rejected")}</span>` : aprobado ? `<span class="insignia">${OK}${ES("aprobada", "approved")}</span>` : `<span class="insignia insignia-punteada">${PEND(12)}${ES("por revisar", "to review")}</span>`; return `<article class="afirmacion"${rech ? " data-rechazada" : ""}><header><span class="cod">${a.cod}</span>${a.diff ? `<span class="diff-marca diff-${a.diff}" style="padding:4px 8px">${ES(a.diff, a.diff === "nuevo" ? "new" : "renamed")}</span>` : ""}${est}</header><p class="evidencia-afirma">${ES(a.es, a.en)}</p><blockquote class="evidencia-cita${a.v === "verificada" ? "" : " evidencia-no-verificada"}">«${ES(a.cita[0], a.cita[1])}»</blockquote>${VER[a.v](a)}<footer><a href="${a.url}">${ES(a.fuente[0], a.fuente[1])}</a><span class="mono">${ES("fuente del fabricante · conflicto de interés declarado", "vendor source · conflict of interest declared")}</span>${!rech && !aprobado ? `<button type="button" class="boton">${ES("Aprobar", "Approve")}</button><button type="button" class="boton boton-sec">${ES("Rechazar", "Reject")}</button>` : ""}</footer></article>`; };
const cabeceraCorrida = (id, extra) => `<div class="tarjeta"><p class="ojo">${ES("Corrida", "Run")}</p><p class="huella"><b>${id}</b></p><p class="meta"><span>2026-09-26 14:02</span><span class="punto">·</span><span>${ES("modelo declarado en ejecucion.json", "model declared in ejecucion.json")}</span><span class="punto">·</span><span>${ES("validador: 1 reintento, luego válida", "validator: 1 retry, then valid")}</span>${extra}</p></div>`;
const investigador = `${head({ es: "Investigador", en: "Researcher" })}
<body>
${mqBar("05 Investigador y revisión de propuestas", "Estado de la maqueta", [["capas", "vista:capas", "capa vencida con comando"], ["propuesta", "vista:propuesta", "propuesta con cambios"], ["aprobado", "vista:aprobado", "aprobado"], ["sin-novedades", "vista:sin-novedades", "sin novedades"]], [["capas", "<b>Semáforo por capa.</b> Las nueve bandas de la Plataforma Ejemplo con su vigencia (símbolo + texto + días). La capa vencida trae el comando exacto para copiar: se corre en Claude Code, jamás desde la app."], ["propuesta", "<b>Propuesta con cambios.</b> Lo que el investigador dejó en «propuestas/»: el diff lo calculó el código (nuevo, renombrado); cada afirmación trae su cita textual y el veredicto del verificador: verificada (curl), no verificable (revisión humana) o no encontrada (rechazo automático). El curador aprueba una por una."], ["aprobado", "<b>Aprobado.</b> Tres afirmaciones aprobadas por el curador, una rechazada por código; la copia a la base lleva «aprobado_por» y la capa vuelve a estar vigente."], ["sin-novedades", "<b>Sin novedades.</b> La huella de la propuesta es igual a la del mapa aprobado: no hay nada que revisar. Se muestra qué fuentes consultó y qué preguntas guía quedaron sin fuente."]])}
${barra("conocimiento")}
<main class="pagina" id="contenido">
  ${encabezado({ es: "Conocimiento · investigador", en: "Knowledge · researcher" }, { es: "Plataforma Ejemplo (ficticia)", en: "Example Platform (fictional)" }, { es: "La IA propone con citas comprobadas por código; el curador aprueba. Nunca corre sola ni en tiempo de ejecución.", en: "The AI proposes with code-checked quotes; the curator approves. It never runs alone nor at runtime." }, `<p class="meta"><span>${ES("mapa aprobado v0.1.0", "approved map v0.1.0")}</span><span class="punto">·</span><span>${ES("consultado 2026-09-26", "checked 2026-09-26")}</span><span class="punto">·</span><span>${ES("7 propuestas en el historial", "7 proposals in history")}</span></p>`)}
  ${pestanas("conocimiento", "investigador.html")}
  <div data-si="vista:capas|aprobado">
  ${sec("Vigencia por capa", "Freshness per layer", ES("Umbrales declarados: 30 y 60 días desde la última verificación, contados con la fecha de consulta. Una capa vencida no se completa por inferencia: se investiga.", "Declared thresholds: 30 and 60 days since the last verification, counted with the query date. An expired layer is never completed by inference: it gets researched."), `<div data-si="vista:capas">${semLista(false)}</div><div data-si="vista:aprobado">${semLista(true)}</div>`)}
  </div>
  <div data-si="vista:aprobado">
  ${sec("Propuesta aprobada", "Approved proposal", "", `<div class="veredicto"><b>${OK}${ES("Aprobada por el curador", "Approved by the curator")}</b><span class="mono">2026-09-26 · 3 ${ES("afirmaciones aprobadas", "claims approved")} · 1 ${ES("rechazada por código", "rejected by code")}</span><span class="mono">${ES("copiada a la base con aprobado_por", "copied to the base with aprobado_por")}</span></div>${cabeceraCorrida("2026-09-26-plataforma-ejemplo-almacenamiento-3f9a1c", `<span class="punto">·</span><span>${ES("6 fuentes consultadas", "6 sources consulted")}</span>`)}<div class="kit-grid" style="margin-top:16px">${AFIRM.map((a) => afirmacion(a, true)).join("")}</div>`)}
  </div>
  <div data-si="vista:propuesta">
  ${sec("Propuesta: almacenamiento", "Proposal: storage", ES("El diff contra el mapa aprobado lo calcula el código por id; el modelo solo redacta. Si el modelo dijera «sin novedades» y el diff no estuviera vacío, gana el diff.", "The diff against the approved map is computed by code, by id; the model only writes. If the model said “no news” and the diff were not empty, the diff wins."), `${cabeceraCorrida("2026-09-26-plataforma-ejemplo-almacenamiento-3f9a1c", `<span class="punto">·</span><span>${ES("6 fuentes consultadas (registro del hook)", "6 sources consulted (hook log)")}</span>`)}
    <div class="conteo" style="margin-top:14px"><span>${ES("diff calculado: 1 nuevo · 1 renombrado · 0 retirados · 0 cambios de madurez", "computed diff: 1 new · 1 renamed · 0 removed · 0 maturity changes")}</span><span>${ES("4 afirmaciones · 2 verificadas · 1 no verificable · 1 no encontrada", "4 claims · 2 verified · 1 not verifiable · 1 not found")}</span></div>
    <div class="kit-grid">${AFIRM.map((a) => afirmacion(a, false)).join("")}</div>
    <div class="kit-fila"><button type="button" class="boton">${ES("Aprobar las marcadas y copiar a la base", "Approve the marked ones and copy to the base")}</button><button type="button" class="boton boton-sec">${ES("Descartar la propuesta", "Discard the proposal")}</button><span class="mono">${ES("aprobar corre scripts/aprobar.mjs: solo el humano", "approving runs scripts/aprobar.mjs: humans only")}</span></div>`)}
  </div>
  <div data-si="vista:sin-novedades">
  ${sec("Corrida sin novedades: gobierno y seguridad", "Run with no news: governance and security", ES("Sin novedades no es «el modelo no encontró nada»: es que la huella canónica de la propuesta es igual a la del mapa aprobado.", "No news does not mean “the model found nothing”: it means the proposal's canonical fingerprint equals the approved map's."), `<div class="veredicto"><b>${OK}${ES("Sin novedades", "No news")}</b><span class="huella">${ES("propuesta", "proposal")} <b>b7e2f0</b>… = ${ES("mapa aprobado", "approved map")} <b>b7e2f0</b>…</span></div>${cabeceraCorrida("2026-09-26-plataforma-ejemplo-gobierno-b7e2f0", "")}
    <div class="dos" style="margin-top:16px"><div class="tarjeta"><h3>${ES("Fuentes consultadas (4)", "Sources consulted (4)")}</h3><ul class="fuentes"><li><a href="https://example.org/ficticia/catalogo">${ES("Documentación ficticia del catálogo", "Fictional catalog documentation")}</a><span class="mono">oficial · 2026-09-26</span></li><li><a href="https://example.org/ficticia/filtros">${ES("Documentación ficticia de filtros", "Fictional filters documentation")}</a><span class="mono">oficial · 2026-09-26</span></li><li><a href="https://example.org/ficticia/notas-2026-09">${ES("Notas de versión ficticias, septiembre", "Fictional release notes, September")}</a><span class="mono">oficial · 2026-09-26</span></li><li><a href="https://example.org/ficticia/blog-seguridad">${ES("Blog ficticio de seguridad", "Fictional security blog")}</a><span class="mono">${ES("tercero", "third party")} · 2026-09-26</span></li></ul></div>
    <div class="tarjeta"><h3>${ES("Preguntas guía", "Guiding questions")}</h3><ul class="pros"><li>${OK}<span>${ES("¿Quién puede ver qué fila? Respondida.", "Who can see which row? Answered.")}</span></li><li>${OK}<span>${ES("¿Se captura el linaje automáticamente? Respondida.", "Is lineage captured automatically? Answered.")}</span></li><li>${OK}<span>${ES("¿Las máscaras aplican en todos los motores? Respondida.", "Do masks apply in every engine? Answered.")}</span></li><li>${ALERTA()}<span>${ES("¿Hay auditoría de accesos con retención declarada? Sin fuente.", "Is there access audit with declared retention? No source.")}<small>${ES("Queda como pregunta abierta en el atlas; no se inventa.", "Stays as an open question in the atlas; nothing is invented.")}</small></span></li></ul></div></div>`)}
  </div>
</main>
${pie}`;

// ---------------------------------------------------------------- 06 base de conocimiento
const EV = [
  { cod: "evi-ejemplo-0142", est: "aprobada", v: "vigente", d: 6, pl: PL[0], crit: CRIT[4], afirma: ["Las tablas limpias se leen en su lugar desde el modelo semántico, sin copia.", "Clean tables are read in place from the semantic model, without a copy."], cita: ["El modelo lee las tablas abiertas directamente mediante el catálogo.", "The model reads the open tables directly through the catalog."], fuente: ["Documentación ficticia del modelo semántico", "Fictional semantic model documentation"], url: "https://example.org/ficticia/semantica", tipo: ["oficial", "official"], fecha: "2026-08-30", mad: ["Disponible de forma general", "Generally available"], coi: ["Fuente del fabricante", "Vendor source"], puntaje: 3, sha: "3f9a" },
  { cod: "evi-norte-0031", est: "aprobada", v: "vigente", d: 12, pl: PL[1], crit: CRIT[3], afirma: ["Las políticas por fila se definen en el catálogo y las aplica cada motor.", "Row policies are defined in the catalog and enforced by every engine."], cita: ["Toda consulta pasa por las políticas de fila del catálogo.", "Every query goes through the catalog's row policies."], fuente: ["Documentación ficticia del catálogo Norte", "Fictional North catalog documentation"], url: "https://example.org/ficticia/norte/catalogo", tipo: ["oficial", "official"], fecha: "2026-09-10", mad: ["Disponible de forma general", "Generally available"], coi: ["Fuente del fabricante", "Vendor source"], puntaje: 4, sha: "77c0" },
  { cod: "evi-sur-0018", est: "aprobada", v: "revisar", d: 41, pl: PL[2], crit: CRIT[5], afirma: ["El asistente de consultas responde en lenguaje natural sobre tablas autorizadas.", "The query assistant answers in natural language over authorised tables."], cita: ["El asistente, en vista previa privada, respeta los permisos del usuario.", "The assistant, in private preview, respects the user's permissions."], fuente: ["Blog ficticio de un integrador", "Fictional integrator blog"], url: "https://example.org/ficticia/integrador/asistente", tipo: ["tercero", "third party"], fecha: "2026-08-16", mad: ["Vista previa privada", "Private preview"], coi: ["Integrador certificado por el fabricante", "Integrator certified by the vendor"], puntaje: 1, sha: "a2d9", tope: true },
  { cod: "pr-0007-a2", est: "propuesta", v: "revisar", d: 34, pl: PL[0], crit: CRIT[1], afirma: ["Nuevo componente: Almacén de objetos frío, en vista previa pública.", "New component: Cold object store, in public preview."], cita: ["El almacén frío está disponible en vista previa pública.", "Cold storage is available in public preview."], fuente: ["Anuncio ficticio del almacén frío", "Fictional cold store announcement"], url: "https://example.org/ficticia/frio", tipo: ["anuncio", "announcement"], fecha: "2026-09-10", mad: ["Vista previa pública", "Public preview"], coi: ["Fuente del fabricante", "Vendor source"], puntaje: null, sha: null },
];
const evidencia = (ev) => `<article class="evidencia${ev.est === "propuesta" ? " evidencia-propuesta" : ""}"><header><span class="cod">${ev.cod}</span>${sem(ev.v, `${ES(VIG_TXT[ev.v][0], VIG_TXT[ev.v][1])} · ${ev.d} d`)}<span class="evidencia-estado">${ES(ev.est, ev.est === "aprobada" ? "approved" : "proposal")}</span></header><p class="conteo"><span>${ES(ev.pl.es, ev.pl.en)}</span><span>${ES(ev.crit.es, ev.crit.en)}</span>${ev.puntaje !== null ? `<span>${ES("puntaje", "score")} ${ev.puntaje}/4${ev.tope ? ` · ${ES("tope por madurez ≤ 2", "maturity cap ≤ 2")}` : ""}</span>` : `<span>${ES("sin puntaje: no participa hasta aprobarse", "no score: takes no part until approved")}</span>`}</p><p class="evidencia-afirma">${ES(ev.afirma[0], ev.afirma[1])}</p><blockquote class="evidencia-cita${ev.sha ? "" : " evidencia-no-verificada"}">«${ES(ev.cita[0], ev.cita[1])}»</blockquote><dl class="evidencia-meta"><div><dt>${ES("Fuente", "Source")}</dt><dd><a href="${ev.url}">${ES(ev.fuente[0], ev.fuente[1])}</a> <span class="mono">${ES(ev.tipo[0], ev.tipo[1])} · ${ev.fecha}</span></dd></div><div><dt>${ES("Madurez", "Maturity")}</dt><dd>${ES(ev.mad[0], ev.mad[1])}</dd></div><div><dt>${ES("Conflicto de interés", "Conflict of interest")}</dt><dd>${ES(ev.coi[0], ev.coi[1])}</dd></div><div><dt>${ES("Verificación", "Verification")}</dt><dd class="mono">${ev.sha ? `curl · 200 · 2026-09-20 · sha256 ${ev.sha}…` : `${ES("no verificable por código · revisión humana", "not verifiable by code · human review")}`}</dd></div></dl>${ev.est === "propuesta" ? `<footer class="kit-fila"><a href="investigador.html" class="enlace-boton">${ES("Revisar en el investigador", "Review in the researcher")}${CHEVRON}</a></footer>` : ""}</article>`;
const selectPl = (aria, ops) => `<span class="select"><select lang="es" data-aria-es="${aria[0]}" data-aria-en="${aria[1]}">${ops.map((o) => `<option>${o[0]}</option>`).join("")}</select><select lang="en" data-aria-es="${aria[0]}" data-aria-en="${aria[1]}">${ops.map((o) => `<option>${o[1]}</option>`).join("")}</select>${CHEVRON}</span>`;
const base = `${head({ es: "Base de conocimiento", en: "Knowledge base" })}
<body>
${mqBar("06 Base de conocimiento", "Estado de la maqueta", [["evidencias", "vista:evidencias", "evidencias"], ["error", "vista:error", "error de carga"], ["instantanea", "vista:instantanea", "instantánea con huella"]], [["evidencias", "<b>Evidencias.</b> Un archivo por entidad; cada evidencia con fuente, fecha, madurez, conflicto de interés, vigencia y verificación. Solo las aprobadas participan del puntaje; la propuesta se ve, pero no cuenta."], ["error", "<b>Error de carga.</b> Una base incompleta no carga: cada error dice archivo, línea, id, campo y regla. Nada se completa por inferencia y ninguna pantalla del caso se calcula hasta que se corrija."], ["instantanea", "<b>Instantánea con huella.</b> Cada versión de la base lleva su huella SHA-256 sobre JSON canónico (RFC 8785). El informe cita la instantánea con la que se calculó; cualquiera la puede volver a verificar."]])}
${barra("conocimiento")}
<main class="pagina" id="contenido">
  ${encabezado({ es: "Conocimiento · base", en: "Knowledge · base" }, { es: "Base de conocimiento", en: "Knowledge base" }, { es: "Capacidades, criterios, evidencias, plataformas y madurez en archivos legibles, versionados y con huella.", en: "Capabilities, criteria, evidence, platforms and maturity in readable, versioned, fingerprinted files." }, `<p class="meta" data-si="vista:evidencias|instantanea"><b>${OK}${ES("base cargada", "base loaded")}</b><span class="punto">·</span><span>${ES("instantánea 2026-09-26", "snapshot 2026-09-26")}</span><span class="punto">·</span>${SHA("8d2c4e", "f31a")}</p><p class="meta" data-si="vista:error"><b>${X()}${ES("la base no carga", "the base does not load")}</b><span class="punto">·</span><span>${ES("3 errores · nada se calcula hasta corregirlos", "3 errors · nothing is computed until fixed")}</span></p>`, false)}
  ${pestanas("conocimiento", "base.html")}
  <div data-si="vista:evidencias">
    <div class="filtros"><label class="campo"><span class="campo-etiqueta">${ES("Plataforma", "Platform")}</span>${selectPl(["Plataforma", "Platform"], [["Todas (4)", "All (4)"], ...PL.map((p) => [p.es, p.en]), ["Plataforma Este (ficticia)", "East Platform (fictional)"]])}</label><label class="campo"><span class="campo-etiqueta">${ES("Criterio", "Criterion")}</span>${selectPl(["Criterio", "Criterion"], [["Todos (11)", "All (11)"], ...CRIT.map((c) => [c.es, c.en])])}</label><label class="campo"><span class="campo-etiqueta">${ES("Estado", "State")}</span>${selectPl(["Estado", "State"], [["Aprobadas y propuestas", "Approved and proposals"], ["Solo aprobadas", "Approved only"], ["Solo propuestas", "Proposals only"]])}</label></div>
    <p class="conteo"><span>${ES("142 evidencias aprobadas", "142 approved pieces of evidence")}</span><span>${ES("7 propuestas", "7 proposals")}</span><span>${ES("4 plataformas", "4 platforms")}</span><span>${ES("11 criterios", "11 criteria")}</span><span>${ES("mostrando 4", "showing 4")}</span></p>
    <div class="kit-grid">${EV.map(evidencia).join("")}</div>
    <p class="kit-nota">${ES("Todas las fuentes de esta maqueta son ficticias (example.org). El autor declara su conflicto de interés en el informe y en la demo.", "Every source in this mockup is fictional (example.org). The author declares their conflict of interest in the report and the demo.")}</p>
  </div>
  <div data-si="vista:error">
    <div class="estado estado-error" role="alert" style="margin-bottom:20px"><b>${ES("La base no carga: 3 errores", "The base does not load: 3 errors")}</b><p>${ES("Formato: archivo:línea:columna · id · campo · regla. Se corrige el dato, nunca se infiere.", "Format: file:line:column · id · field · rule. The data gets fixed, never inferred.")}</p><ul class="error-lista"><li>conocimiento/evidencias/evi-sur-0018.yaml:14:3 · evi-sur-0018 · fecha_verificacion · ${ES("obligatorio, ausente", "required, missing")}</li><li>conocimiento/evidencias/evi-norte-0044.yaml:9:11 · evi-norte-0044 · fuente.conflicto_de_interes · ${ES("obligatorio, ausente", "required, missing")}</li><li>conocimiento/plataformas/plat-este.yaml:21:5 · plat-este · componentes[3].capa · ${ES("«laboratorio» no pertenece a la gramática plataformas-datos", "“laboratorio” is not in the plataformas-datos grammar")}</li></ul></div>
    ${sec("Qué pasa mientras tanto", "What happens meanwhile", "", `<ul class="pros"><li>${X()}<span>${ES("Ninguna comparación ni informe se calcula con una base que no carga.", "No comparison or report is computed with a base that does not load.")}</span></li><li>${X()}<span>${ES("La instantánea anterior (2026-09-12) sigue siendo la vigente para el atlas y la demo.", "The previous snapshot (2026-09-12) remains current for the atlas and the demo.")}</span></li><li>${OK}<span>${ES("El validador corre también en la CI: el error se ve antes de mezclar.", "The validator also runs in CI: the error shows before merging.")}</span></li></ul>`)}
  </div>
  <div data-si="vista:instantanea">
    ${sec("Instantáneas", "Snapshots", ES("Huella SHA-256 sobre el JSON canónico (RFC 8785) de toda la base aprobada. El informe cita la instantánea con la que se calculó.", "SHA-256 fingerprint over the canonical JSON (RFC 8785) of the whole approved base. The report cites the snapshot it was computed with."), `<div class="tabla-marco"><table class="tabla"><thead><tr><th>${ES("Fecha", "Date")}</th><th>${ES("Huella", "Fingerprint")}</th><th>${ES("Evidencias", "Evidence")}</th><th>${ES("Plataformas", "Platforms")}</th><th></th></tr></thead><tbody><tr><td class="mono">2026-09-26 <span class="insignia insignia-suave" style="margin-left:8px">${ES("vigente", "current")}</span></td><td>${SHA("8d2c4e", "f31a")}</td><td class="mono">142</td><td class="mono">4</td><td><button type="button" class="boton boton-sec" style="min-height:34px;padding:0 12px;font-size:14px">${ES("Verificar huella", "Verify fingerprint")}</button></td></tr><tr><td class="mono">2026-09-12</td><td>${SHA("41b9a0", "07de")}</td><td class="mono">139</td><td class="mono">4</td><td><a href="#" class="enlace-boton" style="min-height:34px;font-size:14px">${ES("Ver diferencias", "See differences")}${CHEVRON}</a></td></tr><tr><td class="mono">2026-08-29</td><td>${SHA("c05e17", "9b3c")}</td><td class="mono">131</td><td class="mono">3</td><td></td></tr></tbody></table></div>
    <div class="veredicto"><b>${OK}${ES("Huella verificada", "Fingerprint verified")}</b><span class="mono">${ES("recalculada ahora = 8d2c4e…f31a · la base no cambió desde la instantánea", "recomputed now = 8d2c4e…f31a · the base has not changed since the snapshot")}</span></div>`)}
  </div>
</main>
${pie}`;

// ---------------------------------------------------------------- 07 perfil del caso
const RESTR = [
  { es: "Los datos clínicos residen en el país", en: "Clinical data resides in the country", elimina: ["Plataforma Este (ficticia)", "East Platform (fictional)"], origen: ["jurídica", "legal"] },
  { es: "Sin operación propia 24 × 7: el servicio debe ser gestionado", en: "No in-house 24 × 7 operation: the service must be managed", elimina: null, origen: ["dirección de TI", "IT management"] },
];
const pesos = (o = {}) => { const ws = o.pesos ?? W; return `<ul class="filas pesos-lista">${CRIT.map((c, i) => { const w = ws[i]; const abierto = o.abierto === i; const [lo, hi] = abierto ? [0, 100] : o.pesos ? [Math.round(w * 0.8), Math.round(w * 1.2)] : RANGO[i]; return `<li${c.esencial ? " data-esencial" : ""}${abierto ? " data-abierto" : ""}><span class="peso-nombre"><b>${ES(c.es, c.en)}${c.esencial ? EST() : ""}</b><small>${ES(`origen: ${c.origen[0]}`, `origin: ${c.origen[1]}`)}</small></span><span class="peso-valor">${w}</span><div class="peso-barra" role="img" data-aria-es="${c.es}: peso ${w}, rango ${lo} a ${hi}" data-aria-en="${c.en}: weight ${w}, range ${lo} to ${hi}"><span class="peso-rango" style="left:${lo}%;width:${hi - lo}%"></span><span class="peso-punto" style="left:${w}%"></span></div><span class="peso-meta">${abierto ? `<span class="campo-aviso">${ALERTA(12)}${ES("rango abierto: 0–100", "open range: 0–100")}</span>` : `<span class="mono">${ES(`rango ±20 % → ${lo}–${hi}`, `range ±20 % → ${lo}–${hi}`)}</span>`}</span></li>`; }).join("")}</ul>`; };
const sumaDe = (ws) => ws.reduce((a, b) => a + b, 0);
const W104 = W.map((w, i) => (i === 3 ? 29 : w));
const suma = (ws, ok) => `<div class="suma"${ok ? "" : " data-error"}><span>${ES("Suma de pesos", "Sum of weights")}</span><span class="mono">${sumaDe(ws)}</span>${ok ? `<span class="campo-aviso">${OK}${ES("suma 100", "adds up to 100")}</span>` : `<span class="campo-aviso">${X(12)}${ES(`deben sumar 100: sobran ${sumaDe(ws) - 100}`, `must add up to 100: ${sumaDe(ws) - 100} over`)}</span>`}</div>`;
const restricciones = `<ul class="filas restr">${RESTR.map((r) => `<li><span><b>${ES(r.es, r.en)}</b><br><small class="mono" style="color:var(--tinta-2)">${ES(`origen: ${r.origen[0]}`, `origin: ${r.origen[1]}`)}</small></span>${r.elimina ? `<span class="insignia insignia-llena insignia-larga">${X(12)}${ES("elimina: " + r.elimina[0], "eliminates: " + r.elimina[1])}</span>` : `<span class="insignia insignia-suave">${OK}${ES("todas la cumplen", "all comply")}</span>`}</li>`).join("")}</ul><p class="kit-nota" style="margin-top:10px">${ES("Una restricción eliminatoria saca a la plataforma de la comparación antes de puntuar; queda registrada por qué.", "An eliminating constraint removes the platform from the comparison before scoring; the reason stays on record.")}</p>`;
const implicitas = (aprobado) => `<div class="dos"><div class="tarjeta"><h3>${ES("¿Una plataforma o una combinación?", "One platform or a combination?")}</h3><p class="kit-nota">${ES("Decisión implícita que la herramienta obliga a discutir. Sin respuesta, el perfil no se aprueba.", "An implicit decision the tool forces you to discuss. Without an answer, the profile is not approved.")}</p><label class="opcion"><input type="radio" name="comb"${aprobado ? " checked" : ""}> <span>${ES("Una sola plataforma", "A single platform")}<small>${ES("Menos integración; la decisión de una vía pesa más.", "Less integration; the one-way decision weighs more.")}</small></span></label><label class="opcion"><input type="radio" name="comb"> <span>${ES("Combinación de dos", "A combination of two")}<small>${ES("Fuera del alcance del comparador: se documenta como supuesto.", "Outside the comparator's scope: documented as an assumption.")}</small></span></label>${aprobado ? "" : `<p class="campo-aviso" style="margin-top:8px">${PEND(12)}${ES("sin responder", "unanswered")}</p>`}</div><div class="tarjeta"><h3>${ES("¿Quién opera la plataforma?", "Who operates the platform?")}</h3><label class="opcion"><input type="radio" name="op" checked> <span>${ES("Servicio gestionado por el fabricante", "Vendor-managed service")}</span></label><label class="opcion"><input type="radio" name="op"> <span>${ES("Equipo propio", "In-house team")}</span></label><h3 style="margin-top:14px">${ES("¿Migrar o coexistir con lo actual?", "Migrate or coexist with the current setup?")}</h3><label class="opcion"><input type="radio" name="mig"> <span>${ES("Migrar en fases", "Migrate in phases")}</span></label><label class="opcion"><input type="radio" name="mig" checked> <span>${ES("Coexistir 12 meses", "Coexist for 12 months")}</span></label></div></div>`;
const perfilBloque = (o) => `${sec("Pesos y rangos", "Weights and ranges", ES("Pesos enteros que suman 100; el rango de incertidumbre es relativo al peso (±20 %); cada peso dice quién lo fijó. Criterio esencial (con estrella): su mínimo no se compensa.", "Integer weights adding up to 100; the uncertainty range is relative to the weight (±20 %); each weight says who set it. Essential criterion (with a star): its minimum is not compensated."), `${suma(o.pesos ?? W, o.ok)}${pesos(o)}`)}
  ${sec("Restricciones eliminatorias", "Eliminating constraints", "", restricciones)}
  ${sec("Decisiones implícitas", "Implicit decisions", "", implicitas(o.aprobado))}`;
const perfil = `${head({ es: "Perfil del caso", en: "Case profile" })}
<body>
${mqBar("07 Perfil del caso", "Estado de la maqueta", [["borrador", "vista:borrador", "borrador"], ["suma", "vista:suma", "suma ≠ 100"], ["rango", "vista:rango", "rango abierto"], ["aprobado", "vista:aprobado", "perfil aprobado"]], [["borrador", "<b>Borrador.</b> El perfil del Hospital Ficticio de la Sabana: 11 pesos que suman 100 con rango relativo y origen; dos restricciones (una elimina a la Plataforma Este); tres decisiones implícitas, una sin responder. No se puede aprobar hasta responderla."], ["suma", "<b>Suma ≠ 100.</b> Gobierno subió a 29 y la suma da 104: el aviso va arriba y en la barra; «Aprobar» queda deshabilitado. Símbolo + texto, sin color de alarma."], ["rango", "<b>Rango abierto.</b> «Equipo y habilidades» no tiene rango declarado: la simulación lo tomaría de 0 a 100 y la robustez se diluye. Se avisa y se sugiere el ±20 % por defecto."], ["aprobado", "<b>Perfil aprobado.</b> Sello con fecha y huella; los campos quedan de solo lectura; solo un perfil aprobado se evalúa. «Comparar» lleva a la pantalla 08."]])}
${barra("caso")}
<main class="pagina" id="contenido">
  ${encabezado({ es: "Caso · perfil", en: "Case · profile" }, CASO, { es: "Pesos, rangos, restricciones y las decisiones que suelen quedar implícitas. Un archivo, versionado.", en: "Weights, ranges, constraints and the decisions that usually stay implicit. One file, versioned." }, `<p class="meta" data-si="vista:borrador|suma|rango"><b>${PEND()}${ES("borrador", "draft")}</b><span class="punto">·</span><span>${ES("casos/hospital-sabana.perfil.yaml", "casos/hospital-sabana.perfil.yaml")}</span><span class="punto">·</span><span>${ES("editado 2026-09-26", "edited 2026-09-26")}</span></p><p class="meta" data-si="vista:aprobado"><b>${OK}${ES("aprobado", "approved")}</b><span class="punto">·</span><span>2026-09-26</span><span class="punto">·</span>${SHA("5a71b3", "e9c2")}<span class="punto">·</span><span>${ES("solo lectura", "read only")}</span></p>`, false)}
  ${pestanas("caso", "perfil.html")}
  <div data-si="vista:borrador">${perfilBloque({ ok: true })}<div class="kit-fila"><button type="button" class="boton" disabled>${ES("Aprobar perfil", "Approve profile")}</button><span class="campo-aviso">${PEND(12)}${ES("falta una decisión implícita por responder", "one implicit decision is still unanswered")}</span></div></div>
  <div data-si="vista:suma">${perfilBloque({ ok: false, pesos: W104 })}<div class="kit-fila"><button type="button" class="boton" disabled>${ES("Aprobar perfil", "Approve profile")}</button><span class="campo-aviso">${X(12)}${ES("la suma debe ser 100", "the sum must be 100")}</span></div></div>
  <div data-si="vista:rango">${perfilBloque({ ok: true, abierto: 8 })}<div class="kit-fila"><button type="button" class="boton" disabled>${ES("Aprobar perfil", "Approve profile")}</button><span class="campo-aviso">${ALERTA(12)}${ES("declara el rango de «Equipo y habilidades» (sugerido ±20 % → 4–6)", "declare the range of “Team and skills” (suggested ±20 % → 4–6)")}</span></div></div>
  <div data-si="vista:aprobado"><div class="veredicto"><span class="sello">${OK}${ES("Perfil aprobado", "Profile approved")}</span><span class="mono">2026-09-26 · ${ES("aprobado por el comité del caso", "approved by the case committee")} · v3</span><a href="comparacion.html" class="boton" style="margin-left:auto;text-decoration:none">${ES("Comparar", "Compare")}</a></div>${perfilBloque({ ok: true, aprobado: true })}</div>
</main>
${pie}`;

// ---------------------------------------------------------------- 08 comparación
const NIVEL = ["no soportado", "parcial o con terceros", "soportado con límites", "maduro", "maduro y nativo"];
const NIVEL_EN = ["not supported", "partial or via third parties", "supported with limits", "mature", "mature and native"];
const LIM_CLARA = { ...LIMITANTE, norte: [3, "Catálogo en vista previa (tope ≤ 2) y filas sin política: 1 en un criterio esencial", "Catalog in preview (cap ≤ 2) and rows without policy: 1 in an essential criterion"] };
const totales = (Tt, lim, scores) => { const orden = [...PL].sort((a, b) => Tt[b.id] - Tt[a.id]); return `<ul class="filas totales">${orden.map((p, i) => `<li${i === 0 ? " data-lider" : ""}><span class="total-nombre"><b>${i > 0 ? `${i + 1} · ` : ""}${ES(p.es, p.en)}</b><small>${ES("mínimo de esenciales", "minimum of essentials")} <b>${minEs(scores[p.id])}/4</b> · ${ES("evidencia limitante:", "limiting evidence:")} ${ES(lim[p.id][1], lim[p.id][2])}</small></span><div class="total-barra" role="img" data-aria-es="${p.es}: ${n1(Tt[p.id])} de 100" data-aria-en="${p.en}: ${Tt[p.id].toFixed(1)} of 100"><span style="width:${Tt[p.id]}%"></span><i style="left:${Tt[orden[0].id] - 5}%"></i></div><span class="total-valor">${num(Tt[p.id])}</span><a href="#matriz" class="enlace-boton" style="min-height:32px;font-size:14px">${ES("Ver puntajes", "See scores")}${CHEVRON}</a></li>`).join("")}</ul><p class="leyenda-inline"><span><i style="display:inline-block;width:14px;border-top:1.5px dashed var(--tinta-2)"></i>${ES("banda de empate técnico: 5 puntos bajo la primera (convención declarada)", "technical-tie band: 5 points below the first (declared convention)")}</span><span>${EST()} ${ES("criterio esencial", "essential criterion")}</span></p>`; };
const matriz = (scores, lim) => `<div class="tabla-marco" id="matriz"><table class="tabla matriz"><thead><tr><th>${ES("Criterio", "Criterion")}</th><th>${ES("Peso", "Weight")}</th>${PL.map((p) => `<th>${ES(p.es.replace(" (ficticia)", ""), p.en.replace(" (fictional)", ""))}</th>`).join("")}</tr></thead><tbody>${CRIT.map((c, i) => { const mejor = Math.max(...PL.map((p) => scores[p.id][i])); return `<tr><td>${ES(c.es, c.en)}${c.esencial ? EST() : ""}</td><td class="mono">${c.w}</td>${PL.map((p) => { const s = scores[p.id][i]; const l = lim[p.id][0] === i; return `<td class="mono"${l ? " data-limitante" : ""}${s === mejor && !l ? " data-mejor" : ""}><span class="cap">${s}<small>/4</small></span></td>`; }).join("")}</tr>`; }).join("")}<tr><th>${ES("Total", "Total")}</th><th class="mono">100</th>${PL.map((p) => `<th class="mono">${num(total(scores[p.id]))}</th>`).join("")}</tr></tbody></table></div><p class="leyenda-inline"><span>${ES("subrayado: la mejor en el criterio", "underlined: best on the criterion")}</span><span>${ES("recuadro punteado: evidencia limitante", "dashed box: limiting evidence")}</span><span>${ES("total = suma de peso × puntaje / 4, aritmética entera", "total = sum of weight × score / 4, integer arithmetic")}</span></p><details class="lectura-seccion" style="margin-top:8px"><summary>${ES("Escala 0–4", "0–4 scale")}${CHEVRON}</summary><ul class="pros" style="margin-top:8px">${NIVEL.map((t, i) => `<li><span class="mono">${i}</span><span>${ES(t, NIVEL_EN[i])}${i === 2 ? `<small>${ES("tope si la madurez no es «disponible de forma general»", "cap when maturity is not “generally available”")}</small>` : ""}</span></li>`).join("")}</ul></details>`;
const SCORES = { ejemplo: e.s, norte: n.s, sur: PL[2].s };
const SCORES_CLARA = { ejemplo: e.s, norte: NORTE_CLARA, sur: PL[2].s };
const veredictoEmpate = `<div class="veredicto"><b>${ALERTA(16)}${ES("Empate técnico", "Technical tie")}</b><span>${ES(`Norte y Ejemplo difieren en ${n1(T.norte - T.ejemplo)} puntos, menos de 5. Mismo mínimo de esenciales (3/4): el desempate leximin tampoco los separa.`, `North and Example differ by ${(T.norte - T.ejemplo).toFixed(1)} points, under 5. Same minimum of essentials (3/4): the leximin tiebreak does not separate them either.`)}</span><span class="mono">${ES("perfil v3 · instantánea 2026-09-26 · semilla 20260926", "profile v3 · snapshot 2026-09-26 · seed 20260926")}</span></div>`;
const veredictoClara = `<div class="veredicto"><b>${OK}${ES("Ganadora clara: Plataforma Ejemplo", "Clear winner: Example Platform")}</b><span>${ES(`Ventaja de ${n1(T_CLARA.ejemplo - T_CLARA.norte)} puntos sobre Norte, cuya evidencia limitante cae en un criterio esencial (gobierno 1/4).`, `Lead of ${(T_CLARA.ejemplo - T_CLARA.norte).toFixed(1)} points over North, whose limiting evidence falls on an essential criterion (governance 1/4).`)}</span><span class="mono">${ES("perfil v3 · instantánea 2026-09-26", "profile v3 · snapshot 2026-09-26")}</span></div>`;
const sens = `<div class="dos"><div class="peso"><div class="peso-cabeza"><b>${ES("Gobierno y seguridad", "Governance and security")}${EST()}</b><span class="mono">25</span></div><div class="peso-barra" role="slider" aria-valuemin="0" aria-valuemax="50" aria-valuenow="25" tabindex="0" data-aria-es="Peso de gobierno y seguridad, de 0 a 50" data-aria-en="Weight of governance and security, 0 to 50"><span class="peso-rango" style="left:40%;width:20%"></span><span class="peso-inversion" style="left:${(tInv / 50) * 100}%"></span><span class="peso-inversion" style="left:${(tEmpateSale / 50) * 100}%;border-left-style:dotted"></span><span class="peso-punto" style="left:50%"></span></div><p class="peso-meta"><span class="mono">${ES("rango 0–50 (el doble del peso)", "range 0–50 (twice the weight)")}</span><span class="punto">·</span><span>${ES(`inversión en ${n1(tInv)}`, `reversal at ${tInv.toFixed(1)}`)}</span><span class="punto">·</span><span>${ES(`sale del empate en ${n1(tEmpateSale)}`, `leaves the tie at ${tEmpateSale.toFixed(1)}`)}</span></p><p class="kit-nota" style="margin:10px 0 0">${ES("Los demás pesos se reparten en proporción. Fórmula cerrada, sin barrido: t* = 100·(m_j − m_i) / [(s_ik − s_jk) − (m_i − m_j)].", "The other weights are redistributed proportionally. Closed formula, no sweep: t* = 100·(m_j − m_i) / [(s_ik − s_jk) − (m_i − m_j)].")}</p></div>
  <div class="tarjeta"><h3>${ES("Qué cambia al mover este peso", "What changes when this weight moves")}</h3><ul class="pros"><li>${OK}<span>${ES(`Por debajo de ${n1(tInv)}, Ejemplo pasa al primer lugar.`, `Below ${tInv.toFixed(1)}, Example moves to first place.`)}<small>${ES("punto de inversión exacto", "exact reversal point")}</small></span></li><li>${ALERTA()}<span>${ES(`Entre 0 y ${n1(tEmpateSale)} hay empate técnico; desde ${n1(tEmpateSale)}, Norte gana con claridad.`, `Between 0 and ${tEmpateSale.toFixed(1)} it is a technical tie; from ${tEmpateSale.toFixed(1)}, North wins clearly.`)}<small>${ES("entrada y salida de la banda de 5 puntos", "entry and exit of the 5-point band")}</small></span></li><li>${OK}<span>${ES("Sur sigue tercera en todo el rango.", "South stays third across the whole range.")}<small>${ES("el 2.º y el 3.er lugar no cambian", "2nd and 3rd place do not change")}</small></span></li></ul><div class="tabla-marco" style="margin-top:12px"><table class="tabla"><thead><tr><th>${ES("Peso", "Weight")}</th><th>Ejemplo</th><th>Norte</th><th>Sur</th></tr></thead><tbody>${[0, 10, 25, 35, 50].map((t) => `<tr><td class="mono">${t}</td>${PL.map((p) => `<td class="mono">${num(Tk(p.s, t))}</td>`).join("")}</tr>`).join("")}</tbody></table></div></div></div>`;
const corto = (p) => [p.es.replace(" (ficticia)", ""), p.en.replace(" (fictional)", "")];
const pct = (v) => ES(`${n1(v)} %`, `${v.toFixed(1)} %`);
const milesEs = (x) => String(x).replace(/\B(?=(\d{3})+(?!\d))/g, " ");
const milesEn = (x) => String(x).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
const miles = (x) => ES(milesEs(x), milesEn(x));
const CLASE = { solida: ["sólida", "solid"], moderada: ["moderada", "moderate"], fragil: ["frágil", "fragile"] };
const CLASE_M = { solida: "sólido", moderada: "moderado", fragil: "frágil" }; // «el orden es …»
const enGris = (v) => [UMBRAL.solida, UMBRAL.moderada].some((u) => Math.abs(v - u) < ROB.ic);
const lider = PL.find((p) => p.id === ROB.lider);
const seg = [...PL].filter((p) => p.id !== lider.id).sort((a, b) => ROB.acept[b.id][0] - ROB.acept[a.id][0] || T[b.id] - T[a.id])[0];
const segOtras = ROB_OTRAS.reduce((a, r) => a + r.ganadas[seg.id], 0);
const MIN_CENTRAL = 30; // con menos muestras ganadoras, el vector central es ruido y no se muestra
const [cl, cls] = [CLASE[ROB.clase], ROB.frontera ? [" (frontera)", " (borderline)"] : ["", ""]];
const hayGris = PL.some((p) => enGris(ROB.acept[p.id][0]));
const quePensar = ROB.ganadas[seg.id] >= MIN_CENTRAL
  ? `<p class="kit-nota" style="margin:0 0 8px">${ES(`Vector central de los pesos con los que queda primera (${ROB.ganadas[seg.id]} combinaciones):`, `Central vector of the weights under which it comes first (${ROB.ganadas[seg.id]} combinations):`)}</p><p class="mono" style="color:var(--tinta-2)">${(() => { const v = enteros100(ROB.central[seg.id]); return CRIT.map((c, i) => `${ES(c.es, c.en)} ${v[i]}`).join(" · "); })()}</p>`
  : `<p>${ES(`${ROB.ganadas[seg.id] ? `Solo en ${ROB.ganadas[seg.id]}` : "En ninguna"} de las ${milesEs(ROB.iter)} combinaciones dentro de los rangos queda primera${segOtras ? ` (en ${segOtras} de ${milesEs(3 * ROB.iter)} con las otras tres semillas)` : ""}. Tendría que bajar ${CRIT[K].es.toLowerCase()} por debajo de ${n1(tInv)}, fuera del rango declarado ${RANGO[K][0]}–${RANGO[K][1]} (origen: ${CRIT[K].origen[0]}): eso ya no es incertidumbre sobre los pesos, es cambiar de prioridad. Lo muestra la vista «Sensibilidad».`, `${ROB.ganadas[seg.id] ? `Only in ${ROB.ganadas[seg.id]}` : "In none"} of the ${milesEn(ROB.iter)} combinations within the ranges does it come first${segOtras ? ` (in ${segOtras} of ${milesEn(3 * ROB.iter)} with the other three seeds)` : ""}. ${CRIT[K].en} would have to drop below ${tInv.toFixed(1)}, outside the declared ${RANGO[K][0]}–${RANGO[K][1]} range (origin: ${CRIT[K].origen[1]}): that is no longer uncertainty about the weights, it is a change of priority. The «Sensitivity» view shows it.`)}</p>`;
const robustez = `<div class="dos"><div><div class="tabla-marco"><table class="tabla acept"><thead><tr><th>${ES("Plataforma", "Platform")}</th>${PL.map((_, r) => `<th>${r === 0 ? ES("1.er lugar", "1st place") : ES(`${r + 1}.º`, `${r + 1}${["st", "nd", "rd"][r] ?? "th"}`)}</th>`).join("")}</tr></thead><tbody>${PL.map((p) => `<tr><td>${ES(...corto(p))}</td>${ROB.acept[p.id].map((v, i) => `<td class="mono"${i === 0 && enGris(v) ? " data-gris" : ""}><span class="barra-mini" aria-hidden="true"><span style="width:${v.toFixed(1)}%"></span></span>${pct(v)}</td>`).join("")}</tr>`).join("")}</tbody></table></div><p class="leyenda-inline"><span class="umbral">${ES(`umbrales declarados: ≥ ${UMBRAL.solida} % sólida · ${UMBRAL.moderada}–${UMBRAL.solida} % moderada · &lt; ${UMBRAL.moderada} % frágil`, `declared thresholds: ≥ ${UMBRAL.solida} % solid · ${UMBRAL.moderada}–${UMBRAL.solida} % moderate · &lt; ${UMBRAL.moderada} % fragile`)}</span>${hayGris ? `<span>${ES(`recuadro punteado: zona gris (a menos de ${n1(ROB.ic)} puntos del umbral)`, `dashed box: grey zone (within ${ROB.ic.toFixed(1)} points of the threshold)`)}</span>` : ""}</p></div>
  <div class="tarjeta"><h3>${ES(`Robustez de la recomendación: ${cl[0]}${cls[0]}`, `Robustness of the recommendation: ${cl[1]}${cls[1]}`)}</h3><p>${ES(`${corto(lider)[0]} queda primera en el ${n1(ROB.acept[lider.id][0])} % de las ${milesEs(ROB.iter)} combinaciones de pesos dentro de los rangos del perfil (intervalo de 95 %: ±${n1(ROB.ic)} puntos): el orden es ${CLASE_M[ROB.clase]}.`, `${corto(lider)[1]} comes first in ${ROB.acept[lider.id][0].toFixed(1)} % of the ${milesEn(ROB.iter)} weight combinations within the profile's ranges (95 % interval: ±${ROB.ic.toFixed(1)} points): the order is ${cl[1]}.`)}${ROB.empate >= UMBRAL.moderada ? ` ${ES(`Pero en el ${n1(ROB.empate)} % de ellas la distancia con la segunda es menor de ${MARGEN_EMPATE} puntos: el empate técnico también es estable. Mover los pesos dentro de lo que se declaró no decide; deciden la evidencia limitante y los supuestos.`, `But in ${ROB.empate.toFixed(1)} % of them the gap to second place is under ${MARGEN_EMPATE} points: the technical tie is just as stable. Moving the weights within what was declared does not decide; the limiting evidence and the assumptions do.`)}` : ""}</p><p class="mono" style="color:var(--tinta-2)">sfc32 · ${ES("semilla", "seed")} ${ROB.semilla} · ${miles(ROB.iter)} · ${ES(`muestreo uniforme sobre el politopo (mínimos por transformación, máximos por rechazo: ${milesEs(ROB.intentos)} intentos) · 3 semillas más: ${MISMA_CLASE ? "misma clase" : "cambia la clase"}`, `uniform sampling over the polytope (minimums by transformation, maximums by rejection: ${milesEn(ROB.intentos)} draws) · 3 more seeds: ${MISMA_CLASE ? "same class" : "the class changes"}`)}</p><h3 style="margin-top:14px">${ES(`¿Qué tendría que creer el comité para que gane ${corto(seg)[0]}?`, `What would the committee have to believe for ${corto(seg)[1]} to win?`)}</h3>${quePensar}</div></div>`;
const simulando = `<div class="estado" role="status" style="max-width:520px"><svg class="carga" viewBox="-12 -12 24 24" width="28" height="28" aria-hidden="true"><circle r="9" fill="none" stroke="currentColor" stroke-width="1.6" stroke-dasharray="40 17"/></svg><b>${ES("Simulación en curso", "Simulation running")}</b><p class="mono">6 200 / 10 000 · sfc32 · ${ES("semilla", "seed")} 20260926 · Web Worker</p><div class="progreso" aria-hidden="true"><span style="width:62%"></span></div><p>${ES("Los totales y la sensibilidad ya están; la robustez llega en unos segundos. Puedes seguir leyendo.", "Totals and sensitivity are ready; robustness arrives in a few seconds. You can keep reading.")}</p><button type="button" class="boton boton-sec">${ES("Cancelar", "Cancel")}</button></div>`;
const PROS = {
  ejemplo: { pro: [["Apertura y portabilidad 4/4: tablas abiertas legibles por otros motores", "Openness and portability 4/4: open tables readable by other engines"], ["Almacenamiento 4/4, la mejor del conjunto", "Storage 4/4, best of the set"]], contra: [["IA 2/4 por tope de madurez (agente en vista previa)", "AI 2/4 due to maturity cap (agent in preview)"], ["Equipo y habilidades 2/4: perfil poco común en el mercado local", "Team and skills 2/4: uncommon profile in the local market"]] },
  norte: { pro: [["Gobierno y seguridad 4/4, la mejor y en un criterio esencial", "Governance and security 4/4, best and on an essential criterion"], ["Ingesta 4/4: conectores gestionados", "Ingestion 4/4: managed connectors"]], contra: [["IA 0/4: sin capacidad en el mapa", "AI 0/4: no capability on the map"], ["Apertura 2/4: formato propio en el almacén de archivos", "Openness 2/4: proprietary format in the file store"]] },
  sur: { pro: [["Transformación 4/4: preparación SQL madura", "Transformation 4/4: mature SQL preparation"]], contra: [["Gobierno 2/4 en un criterio esencial: máscaras sin auditoría", "Governance 2/4 on an essential criterion: masks without audit"], ["Consumo 2/4: un solo tablero, sin reportes", "Consumption 2/4: a single dashboard, no reports"]] },
};
const pros = `<div class="kit-grid tres">${PL.map((p) => `<div class="tarjeta"><h3>${ES(p.es, p.en)}</h3><p class="ojo" style="margin:8px 0 4px">${ES("Se destaca", "Stands out")}</p><ul class="pros">${PROS[p.id].pro.map((t) => `<li>${OK}<span>${ES(t[0], t[1])}</span></li>`).join("")}</ul><p class="ojo" style="margin:12px 0 4px">${ES("Se queda corta", "Falls short")}</p><ul class="pros">${PROS[p.id].contra.map((t) => `<li>${X()}<span>${ES(t[0], t[1])}</span></li>`).join("")}</ul></div>`).join("")}</div><p class="kit-nota">${ES("Por reglas, contra el ancla de la escala (4/4) y contra la mejor del conjunto; nunca contra el promedio, que cambiaría al agregar una plataforma.", "By rules, against the scale anchor (4/4) and against the best of the set; never against the average, which would change when a platform is added.")}</p>`;
const comparacion = `${head({ es: "Comparación", en: "Comparison" })}
<body>
${mqBar("08 Comparación", "Estado de la maqueta", [["empate", "vista:empate", "empate técnico"], ["clara", "vista:clara", "ganadora clara"], ["sensibilidad", "vista:sensibilidad", "sensibilidad"], ["simulando", "vista:simulando", "simulación en curso"], ["robustez", "vista:robustez", "robustez"], ["pros", "vista:pros", "pros y contras"]], [["empate", "<b>Empate técnico.</b> Norte y Ejemplo a menos de 5 puntos (convención declarada) con el mismo mínimo de esenciales: se declara empate, no se esconde. Cada plataforma muestra su evidencia limitante; la matriz marca la mejor por criterio y el tope por madurez."], ["clara", "<b>Ganadora clara.</b> Otra base: la evidencia limitante de Norte cae a 1 en un criterio esencial y Ejemplo gana por más de 5 puntos."], ["sensibilidad", "<b>Sensibilidad.</b> Se mueve un peso (gobierno, de 0 al doble) y el control marca el punto de inversión (línea discontinua) y la salida del empate (punteada). Fórmula cerrada; tabla de totales por valor."], ["simulando", "<b>Simulación en curso.</b> La robustez corre en un Web Worker con semilla; la pantalla dice qué corre, cuánto lleva y deja seguir leyendo."], ["robustez", "<b>Robustez.</b> Aceptabilidad por posición calculada: sfc32 con semilla, 10 000 combinaciones uniformes sobre el politopo de rangos del perfil, umbrales 70 / 50 declarados. En este caso el orden es sólido y el empate también; como ninguna combinación dentro de los rangos cambia a la primera, la pregunta «¿qué tendría que creer el comité?» se responde con el punto de inversión. La zona gris solo se marca si el intervalo cruza un umbral."], ["pros", "<b>Pros y contras por reglas.</b> Dónde se destaca y dónde se queda corta cada plataforma, contra la escala y contra la mejor; nunca contra el promedio."]])}
${barra("caso")}
<main class="pagina" id="contenido">
  ${encabezado({ es: "Caso · comparación", en: "Case · comparison" }, CASO, { es: "Tres plataformas puntuadas con evidencia fechada; la cuarta quedó fuera por restricción. Cualquiera repite el cálculo y obtiene los mismos bytes.", en: "Three platforms scored with dated evidence; the fourth was ruled out by a constraint. Anyone can repeat the computation and get the same bytes." }, `<p class="meta"><b>${OK}${ES("perfil v3 aprobado", "profile v3 approved")}</b><span class="punto">·</span><span>${ES("instantánea 2026-09-26", "snapshot 2026-09-26")}</span><span class="punto">·</span>${SHA("8d2c4e", "f31a")}<span class="punto">·</span><span>${ES("fecha de evaluación 2026-09-26", "evaluation date 2026-09-26")}</span><span class="punto">·</span><span>${ES("Plataforma Este eliminada: residencia de datos", "East Platform eliminated: data residency")}</span></p>`, false)}
  ${pestanas("caso", "comparacion.html")}
  <ul class="niveles kit-niveles" aria-label="Vistas de la comparación"><li><a href="#totales" data-si="vista:empate|clara" aria-current="page"><span class="n">a</span>${ES("Totales", "Totals")}</a><a href="#totales" data-si="vista:sensibilidad|simulando|robustez|pros"><span class="n">a</span>${ES("Totales", "Totals")}</a></li><li><a href="#sens" data-si="vista:sensibilidad" aria-current="page"><span class="n">b</span>${ES("Sensibilidad", "Sensitivity")}</a><a href="#sens" data-si="vista:empate|clara|simulando|robustez|pros"><span class="n">b</span>${ES("Sensibilidad", "Sensitivity")}</a></li><li><a href="#rob" data-si="vista:simulando|robustez" aria-current="page"><span class="n">c</span>${ES("Robustez", "Robustness")}</a><a href="#rob" data-si="vista:empate|clara|sensibilidad|pros"><span class="n">c</span>${ES("Robustez", "Robustness")}</a></li><li><a href="#pros" data-si="vista:pros" aria-current="page"><span class="n">d</span>${ES("Pros y contras", "Pros and cons")}</a><a href="#pros" data-si="vista:empate|clara|sensibilidad|simulando|robustez"><span class="n">d</span>${ES("Pros y contras", "Pros and cons")}</a></li></ul>
  <div data-si="vista:empate|sensibilidad|simulando|robustez|pros">
  ${sec("Totales", "Totals", "", `${veredictoEmpate}${totales(T, LIMITANTE, SCORES)}`, ' id="totales"')}
  </div>
  <div data-si="vista:clara">
  ${sec("Totales", "Totals", "", `${veredictoClara}${totales(T_CLARA, LIM_CLARA, SCORES_CLARA)}`)}
  ${sec("Puntajes por criterio", "Scores per criterion", "", matriz(SCORES_CLARA, LIM_CLARA))}
  </div>
  <div data-si="vista:empate">
  ${sec("Puntajes por criterio", "Scores per criterion", ES("0–4 con tope por madurez antes del mínimo; cada puntaje se remonta a una evidencia aprobada (toca uno para verla en la base).", "0–4 with the maturity cap before the minimum; each score traces back to an approved piece of evidence (tap one to see it in the base)."), matriz(SCORES, LIMITANTE))}
  </div>
  <div data-si="vista:sensibilidad">
  ${sec("Sensibilidad de un factor", "One-factor sensitivity", ES("Mueves un peso y ves exactamente dónde cambia la ganadora, dónde entra en empate y si cambian el segundo y el tercero.", "Move one weight and see exactly where the winner changes, where it enters a tie and whether 2nd and 3rd change."), sens, ' id="sens"')}
  </div>
  <div data-si="vista:simulando">
  ${sec("Robustez por simulación", "Robustness by simulation", "", simulando, ' id="rob"')}
  </div>
  <div data-si="vista:robustez">
  ${sec("Robustez por simulación", "Robustness by simulation", ES("10 000 combinaciones de pesos dentro de los rangos del perfil, con semilla. En qué porcentaje gana cada plataforma y qué tan sólida es la recomendación; los umbrales están declarados, no escondidos.", "10 000 weight combinations within the profile's ranges, seeded. How often each platform wins and how solid the recommendation is; thresholds declared, not hidden."), robustez)}
  </div>
  <div data-si="vista:pros">
  ${sec("Pros y contras", "Pros and cons", "", pros, ' id="pros"')}
  </div>
</main>
${pie}`;

for (const [f, h] of [["investigador.html", investigador], ["base.html", base], ["perfil.html", perfil], ["comparacion.html", comparacion]]) { fs.writeFileSync(OUT + f, h); console.log(f, (h.length / 1024).toFixed(1), "KB"); }
