// Cadenas de interfaz de prueba (D-S1-06): el paquete no las trae; la app entrega las suyas. Estas son las
// de la maqueta aprobada, para que los golden files se parezcan a la referencia.
import type { TextosMotor } from "../../src/index";

export const TEXTOS: Record<string, TextosMotor> = {
  es: {
    componentes: ["{n} componente", "{n} componentes"],
    fuentes: ["{n} fuente", "{n} fuentes"],
    sinBloque: "sin bloque",
    transversales: "TRANSVERSALES · ABARCAN TODAS LAS CAPAS",
    envia: "Conecta con {nombre}, {modos}",
    recibe: "Recibe de {nombre}, {modos}",
    y: " y ",
    componentesDe: "Componentes",
    dias: "{n} d",
    porRevisar: "Por revisar: verificado hace {n} días.",
    vencido: "Vencido: verificado hace {n} días.",
    titulo: { "nivel-1": "{sujeto} · visión general", "nivel-2": "{sujeto} · componentes", recorrido: "{sujeto} · {recorrido}" },
    descripcion: {
      "nivel-1": "Mapa de {sujeto}: {capas} capas de izquierda a derecha y {franjas} franjas transversales abajo.",
      "nivel-2": "Componentes de {sujeto}: {nodos} componentes en {capas} capas y {franjas} franjas.",
      recorrido: "Recorrido «{recorrido}» sobre los componentes de {sujeto}.",
    },
    paso: "Paso {numero}: {que}",
    hacia: "Hacia {nombre}, {modo}: {que}",
    desde: "Desde {nombre}, {modo}: {que}",
    recorridoDe: "Recorrido: {titulo}",
    ramas: { paralela: "Se divide en ramas que ocurren a la vez:", alternativa: "Sigue por una de estas ramas:" },
    ficha: {
      queHace: "Qué hace",
      porQueImporta: "Por qué importa",
      terminos: "Términos",
      glosario: "glosario",
      madurez: "Madurez",
      fuentes: "Fuentes",
      verificado: "verificado {fecha}",
      consultado: "consultado {fecha}",
      tipoFuente: { oficial: "oficial", tercero: "tercero" },
    },
    leyenda: {
      tipos: "Tipos de componente",
      modos: "Cómo viaja el dato",
      madurez: "Madurez",
      vigencia: "Vigencia",
      reglaVigencia: "Por revisar desde {revisar} días; vencido desde {vencido} días.",
      vigente: "Vigente",
      porRevisar: "Por revisar",
      vencido: "Vencido",
      notaMarcas: "Los nombres comerciales se usan para identificar productos; ningún logo, ícono ni color de marca.",
    },
  },
  en: {
    componentes: ["{n} component", "{n} components"],
    fuentes: ["{n} source", "{n} sources"],
    sinBloque: "no block",
    transversales: "CROSS-CUTTING · SPAN EVERY LAYER",
    envia: "Connects to {nombre}, {modos}",
    recibe: "Receives from {nombre}, {modos}",
    y: " and ",
    componentesDe: "Components",
    dias: "{n} d",
    porRevisar: "To review: verified {n} days ago.",
    vencido: "Expired: verified {n} days ago.",
    titulo: { "nivel-1": "{sujeto} · overview", "nivel-2": "{sujeto} · components", recorrido: "{sujeto} · {recorrido}" },
    descripcion: {
      "nivel-1": "{sujeto} map: {capas} layers from left to right and {franjas} cross-cutting bands below.",
      "nivel-2": "{sujeto} components: {nodos} components in {capas} layers and {franjas} bands.",
      recorrido: "Journey “{recorrido}” over the components of {sujeto}.",
    },
    paso: "Step {numero}: {que}",
    hacia: "To {nombre}, {modo}: {que}",
    desde: "From {nombre}, {modo}: {que}",
    recorridoDe: "Journey: {titulo}",
    ramas: { paralela: "Splits into branches that happen at the same time:", alternativa: "Continues along one of these branches:" },
    ficha: {
      queHace: "What it does",
      porQueImporta: "Why it matters",
      terminos: "Terms",
      glosario: "glossary",
      madurez: "Maturity",
      fuentes: "Sources",
      verificado: "verified {fecha}",
      consultado: "checked {fecha}",
      tipoFuente: { oficial: "official", tercero: "third party" },
    },
    leyenda: {
      tipos: "Component types",
      modos: "How the data travels",
      madurez: "Maturity",
      vigencia: "Freshness",
      reglaVigencia: "To review from {revisar} days; expired from {vencido} days.",
      vigente: "Current",
      porRevisar: "To review",
      vencido: "Expired",
      notaMarcas: "Trade names identify products; no logos, icons or brand colours.",
    },
  },
};
