// Cadenas de interfaz de prueba (D-S1-06): el paquete no las trae; la app entrega las suyas. Estas son las
// de la maqueta aprobada, para que los golden files se parezcan a la referencia.
import type { TextosMotor } from "../../src/index";

export const TEXTOS: Record<string, TextosMotor> = {
  es: {
    componentes: { one: "{n} componente", other: "{n} componentes" },
    fuentes: { one: "{n} fuente", other: "{n} fuentes" },
    sinBloque: "sin bloque",
    transversales: "TRANSVERSALES · ABARCAN TODAS LAS CAPAS",
    envia: "Conecta con {nombre}, {modos}",
    recibe: "Recibe de {nombre}, {modos}",
    y: " y ",
    componentesDe: "Componentes",
    dias: "{n} d",
    porRevisar: "Por revisar: verificado hace {n} días.",
    vencido: "Vencido: verificado hace {n} días.",
    titulo: { "nivel1": "{sujeto} · visión general", "nivel2": "{sujeto} · componentes", recorrido: "{sujeto} · {recorrido}", bloque: "{sujeto} · {bloque}", compare: "Lado a lado: {sujetos}" },
    descripcion: {
      "nivel1": "Mapa de {sujeto}: {capas} capas de izquierda a derecha y {franjas} franjas transversales abajo.",
      "nivel2": "Componentes de {sujeto}: {nodos} componentes en {capas} capas y {franjas} franjas.",
      recorrido: "Recorrido «{recorrido}» sobre los componentes de {sujeto}.",
      bloque: "{bloque} de {sujeto}: sus componentes, uno bajo otro; una línea entre dos es un flujo entre ellos.",
      compare: "{mapas} plataformas alineadas por banda: las {capas} capas y las {franjas} franjas en columnas, una plataforma por fila.",
    },
    paso: "Paso {numero}: {que}",
    hacia: "Hacia {nombre}, {modo}: {que}",
    desde: "Desde {nombre}, {modo}: {que}",
    recorridoDe: "Recorrido: {titulo}",
    ramas: { paralela: "Se divide en ramas que ocurren a la vez:", alternativa: "Sigue por una de estas ramas:" },
    ficha: {
      queHace: "Qué hace",
      porQueImporta: "Por qué importa",
      terminos: "Términos",
      glosario: "glosario",
      madurez: "Madurez",
      fuentes: "Fuentes",
      verificado: "verificado {fecha}",
      consultado: "consultado {fecha}",
      tipoFuente: { oficial: "oficial", tercero: "tercero" },
    },
    lado: {
      fila: { one: "v{version} · verificado hace {n} día", other: "v{version} · verificado hace {n} días" },
      filaRevisar: "v{version} · por revisar · {n} días",
      filaVencido: "v{version} · vencido · {n} días",
      comp: { one: "{n} comp.", other: "{n} comp." },
      sinComponentes: "sin componentes",
      marcas: { nuevo: "nuevo", retirado: "retirado", renombrado: "renombrado", madurez: "madurez" },
      detalle: {
        nuevo: "Nuevo componente en {banda}, {madurez}.",
        retirado: "Retirado del mapa.",
        renombrado: "Antes «{antes}». Mismo componente.",
        madurez: "Madurez: de {antes} a {ahora}.",
        otros: { one: "Además, {n} cambio en flujos o pasos.", other: "Además, {n} cambios en flujos o pasos." },
        ninguna: "Sin diferencias entre las dos versiones.",
      },
    },
    leyenda: {
      tipos: "Tipos de componente",
      modos: "Cómo viaja el dato",
      madurez: "Madurez",
      vigencia: "Vigencia",
      reglaVigencia: "Por revisar desde {revisar} días; vencido desde {vencido} días.",
      vigente: "Vigente",
      porRevisar: "Por revisar",
      vencido: "Vencido",
      haz: "Varios modos en una conexión: línea gruesa y una etiqueta que dice cuáles, en orden.",
      notaMarcas: "Los nombres comerciales se usan para identificar productos; ningún logo, ícono ni color de marca.",
    },
  },
  en: {
    componentes: { one: "{n} component", other: "{n} components" },
    fuentes: { one: "{n} source", other: "{n} sources" },
    sinBloque: "no block",
    transversales: "CROSS-CUTTING · SPAN EVERY LAYER",
    envia: "Connects to {nombre}, {modos}",
    recibe: "Receives from {nombre}, {modos}",
    y: " and ",
    componentesDe: "Components",
    dias: "{n} d",
    porRevisar: "To review: verified {n} days ago.",
    vencido: "Expired: verified {n} days ago.",
    titulo: { "nivel1": "{sujeto} · overview", "nivel2": "{sujeto} · components", recorrido: "{sujeto} · {recorrido}", bloque: "{sujeto} · {bloque}", compare: "Side by side: {sujetos}" },
    descripcion: {
      "nivel1": "{sujeto} map: {capas} layers from left to right and {franjas} cross-cutting bands below.",
      "nivel2": "{sujeto} components: {nodos} components in {capas} layers and {franjas} bands.",
      recorrido: "Journey “{recorrido}” over the components of {sujeto}.",
      bloque: "{bloque} in {sujeto}: its components, one below the other; a line between two is a flow between them.",
      compare: "{mapas} platforms aligned by band: the {capas} layers and the {franjas} bands as columns, one platform per row.",
    },
    paso: "Step {numero}: {que}",
    hacia: "To {nombre}, {modo}: {que}",
    desde: "From {nombre}, {modo}: {que}",
    recorridoDe: "Journey: {titulo}",
    ramas: { paralela: "Splits into branches that happen at the same time:", alternativa: "Continues along one of these branches:" },
    ficha: {
      queHace: "What it does",
      porQueImporta: "Why it matters",
      terminos: "Terms",
      glosario: "glossary",
      madurez: "Maturity",
      fuentes: "Sources",
      verificado: "verified {fecha}",
      consultado: "checked {fecha}",
      tipoFuente: { oficial: "official", tercero: "third party" },
    },
    lado: {
      fila: { one: "v{version} · verified {n} day ago", other: "v{version} · verified {n} days ago" },
      filaRevisar: "v{version} · to review · {n} days",
      filaVencido: "v{version} · expired · {n} days",
      comp: { one: "{n} comp.", other: "{n} comp." },
      sinComponentes: "no components",
      marcas: { nuevo: "new", retirado: "removed", renombrado: "renamed", madurez: "maturity" },
      detalle: {
        nuevo: "New component in {banda}, {madurez}.",
        retirado: "Removed from the map.",
        renombrado: "Formerly “{antes}”. Same component.",
        madurez: "Maturity: from {antes} to {ahora}.",
        otros: { one: "Also, {n} change in flows or steps.", other: "Also, {n} changes in flows or steps." },
        ninguna: "No differences between the two versions.",
      },
    },
    leyenda: {
      tipos: "Component types",
      modos: "How the data travels",
      madurez: "Maturity",
      vigencia: "Freshness",
      reglaVigencia: "To review from {revisar} days; expired from {vencido} days.",
      vigente: "Current",
      porRevisar: "To review",
      vencido: "Expired",
      haz: "Several modes on one connection: a thick line and a label that says which, in order.",
      notaMarcas: "Trade names identify products; no logos, icons or brand colours.",
    },
  },
};
